services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=rcpchCensusUser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rcpchCensusdb
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - RCPCH_CENSUS_ENGINE_SECRET_KEY=mysecretkey
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://localhost,https://0.0.0.0
      - POSTCODES_IO_API_URL=https://api.postcodes.io
      - POSTCODES_IO_API_KEY=1234567890
    command: >
      sh -c "/app/s/wait-for-db.sh && python -u manage.py collectstatic --noinput && python -u manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

  db:
    image: postgis/postgis:15-3.4
    platform: linux/amd64
    volumes:
      - "datadb_postgis:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=rcpchCensusUser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rcpchCensusdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    tty: true
    stdin_open: true

  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    environment:
      # Add these environment variables to pg_tileserv
      - TS_TILE_EXTENT=8192 # Doubles the resolution within the tile
      - TS_TILE_BUFFER=256 # Captures features that sit right on the edge of a tile
      - HTTP_CORS_ORIGIN=*
      - DATABASE_URL=postgresql://rcpchCensusUser:password@db:5432/rcpchCensusdb
    ports:
      - 7800:7800
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  datadb_postgis:
