[pytest]
DJANGO_SETTINGS_MODULE = rcpch_census_platform.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -v --tb=short --reuse-db