import pytest

# API endpoint URLs (no /api prefix - routes are at root level)
INDICES_OF_MULTIPLE_DEPRIVATION_URL = "/indices_of_multiple_deprivation"
INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL = "/index_of_multiple_deprivation_quantile"

ENGLISH_2025_IMD_TEST_DATA = [
    {
        "Postcode": "AL1 3AG",
        "LSOA Name": "St Albans 012F",
        "IMD Rank": "20573",
        "IMD Decile": "7",
    },
    {
        "Postcode": "B1 1AA",
        "LSOA Name": "Birmingham 138D",
        "IMD Rank": "27277",
        "IMD Decile": "9",
    },
    {
        "Postcode": "BA1 1AL",
        "LSOA Name": "Bath and North East Somerset 009C",
        "IMD Rank": "10184",
        "IMD Decile": "4",
    },
    {
        "Postcode": "BB1 1BB",
        "LSOA Name": "Blackburn with Darwen 006A",
        "IMD Rank": "2243",
        "IMD Decile": "1",
    },
    {
        "Postcode": "BD1 1AH",
        "LSOA Name": "Bradford 065C",
        "IMD Rank": "2494",
        "IMD Decile": "1",
    },
    {
        "Postcode": "BN1 1AB",
        "LSOA Name": "Brighton and Hove 027A",
        "IMD Rank": "8689",
        "IMD Decile": "3",
    },
    {
        "Postcode": "BS1 4AP",
        "LSOA Name": "Bristol 061B",
        "IMD Rank": "15885",
        "IMD Decile": "5",
    },
    {
        "Postcode": "CB2 1ND",
        "LSOA Name": "Cambridge 014A",
        "IMD Rank": "19027",
        "IMD Decile": "6",
    },
    {
        "Postcode": "CH1 1BA",
        "LSOA Name": "Cheshire West and Chester 034H",
        "IMD Rank": "22759",
        "IMD Decile": "7",
    },
    {
        "Postcode": "CM1 1BY",
        "LSOA Name": "Chelmsford 022A",
        "IMD Rank": "22220",
        "IMD Decile": "7",
    },
    {
        "Postcode": "CO1 1AU",
        "LSOA Name": "Colchester 007B",
        "IMD Rank": "19132",
        "IMD Decile": "6",
    },
    {
        "Postcode": "CV1 2DS",
        "LSOA Name": "Coventry 031F",
        "IMD Rank": "8179",
        "IMD Decile": "3",
    },
    {
        "Postcode": "DE1 2BA",
        "LSOA Name": "Derby 013G",
        "IMD Rank": "3751",
        "IMD Decile": "2",
    },
    {
        "Postcode": "DH1 1AA",
        "LSOA Name": "County Durham 030H",
        "IMD Rank": "28771",
        "IMD Decile": "9",
    },
    {
        "Postcode": "DN1 2JA",
        "LSOA Name": "Doncaster 019C",
        "IMD Rank": "11609",
        "IMD Decile": "4",
    },
    {
        "Postcode": "EX1 1AF",
        "LSOA Name": "Exeter 008F",
        "IMD Rank": "10978",
        "IMD Decile": "4",
    },
    {
        "Postcode": "FY1 1AQ",
        "LSOA Name": "Blackpool 006A",
        "IMD Rank": "36",
        "IMD Decile": "1",
    },
    {
        "Postcode": "GL1 1AH",
        "LSOA Name": "Gloucester 002D",
        "IMD Rank": "15628",
        "IMD Decile": "5",
    },
    {
        "Postcode": "GU1 3AJ",
        "LSOA Name": "Guildford 013E",
        "IMD Rank": "23272",
        "IMD Decile": "7",
    },
    {
        "Postcode": "HP1 1DN",
        "LSOA Name": "Dacorum 015E",
        "IMD Rank": "13817",
        "IMD Decile": "5",
    },
    {
        "Postcode": "IP1 1AE",
        "LSOA Name": "Ipswich 007G",
        "IMD Rank": "4017",
        "IMD Decile": "2",
    },
    {
        "Postcode": "L1 3BG",
        "LSOA Name": "Liverpool 061C",
        "IMD Rank": "13793",
        "IMD Decile": "5",
    },
    {
        "Postcode": "LE2 7LT",
        "LSOA Name": "Leicester 030C",
        "IMD Rank": "12779",
        "IMD Decile": "4",
    },
    {
        "Postcode": "LS1 1BA",
        "LSOA Name": "Leeds 111A",
        "IMD Rank": "15567",
        "IMD Decile": "5",
    },
    {
        "Postcode": "M1 5AL",
        "LSOA Name": "Manchester 057C",
        "IMD Rank": "16860",
        "IMD Decile": "5",
    },
    {
        "Postcode": "ME14 1BQ",
        "LSOA Name": "Maidstone 004I",
        "IMD Rank": "4275",
        "IMD Decile": "2",
    },
    {
        "Postcode": "MK9 3BL",
        "LSOA Name": "Milton Keynes 014E",
        "IMD Rank": "6182",
        "IMD Decile": "2",
    },
    {
        "Postcode": "NE1 1AE",
        "LSOA Name": "Newcastle upon Tyne 036C",
        "IMD Rank": "11273",
        "IMD Decile": "4",
    },
    {
        "Postcode": "NG1 6EE",
        "LSOA Name": "Nottingham 028F",
        "IMD Rank": "29480",
        "IMD Decile": "9",
    },
    {
        "Postcode": "NR1 1JR",
        "LSOA Name": "Norwich 014F",
        "IMD Rank": "11877",
        "IMD Decile": "4",
    },
    {
        "Postcode": "PE1 5BA",
        "LSOA Name": "Peterborough 013G",
        "IMD Rank": "2680",
        "IMD Decile": "1",
    },
    {
        "Postcode": "PO1 3AL",
        "LSOA Name": "Portsmouth 027A",
        "IMD Rank": "7484",
        "IMD Decile": "3",
    },
    {
        "Postcode": "PR1 1AA",
        "LSOA Name": "Preston 017B",
        "IMD Rank": "5319",
        "IMD Decile": "2",
    },
    {
        "Postcode": "RG1 1BA",
        "LSOA Name": "Reading 019B",
        "IMD Rank": "16119",
        "IMD Decile": "5",
    },
    {
        "Postcode": "RH1 1AT",
        "LSOA Name": "Reigate and Banstead 011I",
        "IMD Rank": "18051",
        "IMD Decile": "6",
    },
    {
        "Postcode": "S1 2AA",
        "LSOA Name": "Sheffield 075G",
        "IMD Rank": "8672",
        "IMD Decile": "3",
    },
    {
        "Postcode": "SE1 7PB",
        "LSOA Name": "Lambeth 036A",
        "IMD Rank": "23019",
        "IMD Decile": "7",
    },
    {
        "Postcode": "SO15 2NP",
        "LSOA Name": "Southampton 023A",
        "IMD Rank": "16720",
        "IMD Decile": "5",
    },
    {
        "Postcode": "SP1 2DG",
        "LSOA Name": "Wiltshire 058C",
        "IMD Rank": "16528",
        "IMD Decile": "5",
    },
    {
        "Postcode": "SS0 7AG",
        "LSOA Name": "Southend-on-Sea 010E",
        "IMD Rank": "6098",
        "IMD Decile": "2",
    },
    {
        "Postcode": "ST1 1AA",
        "LSOA Name": "Stoke-on-Trent 015D",
        "IMD Rank": "553",
        "IMD Decile": "1",
    },
    {
        "Postcode": "SY1 1AA",
        "LSOA Name": "Shropshire 019E",
        "IMD Rank": "15507",
        "IMD Decile": "5",
    },
    {
        "Postcode": "TA1 1DT",
        "LSOA Name": "Somerset West and Taunton 011C",
        "IMD Rank": "20334",
        "IMD Decile": "7",
    },
    {
        "Postcode": "TF1 1AA",
        "LSOA Name": "Telford and Wrekin 012D",
        "IMD Rank": "6816",
        "IMD Decile": "3",
    },
    {
        "Postcode": "TN1 1DD",
        "LSOA Name": "Tunbridge Wells 012D",
        "IMD Rank": "27238",
        "IMD Decile": "9",
    },
    {
        "Postcode": "TR1 1AA",
        "LSOA Name": "Cornwall 044A",
        "IMD Rank": "23082",
        "IMD Decile": "7",
    },
    {
        "Postcode": "WA1 1BA",
        "LSOA Name": "Warrington 018F",
        "IMD Rank": "2887",
        "IMD Decile": "1",
    },
    {
        "Postcode": "WR1 1DU",
        "LSOA Name": "Worcester 007C",
        "IMD Rank": "11457",
        "IMD Decile": "4",
    },
]

ENGLISH_2019_IMD_TEST_DATA = [
    {
        "Postcode": "B1 1AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033625",
        "LSOA Name": "Birmingham 138D E01033625",
        "Index of Multiple Deprivation Rank": "20275",
        "Index of Multiple Deprivation Decile": "7",
        "Income Rank": "32605",
        "Income Decile": "10",
        "Income Score": "0.015",
        "Employment Rank": "32623",
        "Employment Decile": "10",
        "Employment Score": "0.014",
        "Education and Skills Rank": "22558",
        "Education and Skills Decile": "7",
        "Health and Disability Rank": "20445",
        "Health and Disability Decile": "7",
        "Crime Rank": "25008",
        "Crime Decile": "8",
        "Barriers to Housing and Services Rank": "1817",
        "Barriers to Housing and Services Decile": "1",
        "Living Environment Rank": "3304",
        "Living Environment Decile": "2",
        "IDACI Rank": "28766",
        "IDACI Decile": "9",
        "IDACI Score": "0.042",
        "IDAOPI Rank": "17376",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.12",
    },
    {
        "Postcode": "SE1 7PB",
        "Postcode Status": "Live",
        "LSOA code": "E01003013",
        "LSOA Name": "Lambeth 036A E01003013",
        "Index of Multiple Deprivation Rank": "21865",
        "Index of Multiple Deprivation Decile": "7",
        "Income Rank": "30923",
        "Income Decile": "10",
        "Income Score": "0.029",
        "Employment Rank": "32583",
        "Employment Decile": "10",
        "Employment Score": "0.015",
        "Education and Skills Rank": "31964",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "15030",
        "Health and Disability Decile": "5",
        "Crime Rank": "16073",
        "Crime Decile": "5",
        "Barriers to Housing and Services Rank": "9583",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "2249",
        "Living Environment Decile": "1",
        "IDACI Rank": "18729",
        "IDACI Decile": "6",
        "IDACI Score": "0.106",
        "IDAOPI Rank": "22641",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.084",
    },
    {
        "Postcode": "M1 5AL",
        "Postcode Status": "Live",
        "LSOA code": "E01033662",
        "LSOA Name": "Manchester 057C E01033662",
        "Index of Multiple Deprivation Rank": "8998",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "28159",
        "Income Decile": "9",
        "Income Score": "0.042",
        "Employment Rank": "27682",
        "Employment Decile": "9",
        "Employment Score": "0.041",
        "Education and Skills Rank": "17387",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "4967",
        "Health and Disability Decile": "2",
        "Crime Rank": "1122",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "3709",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "439",
        "Living Environment Decile": "1",
        "IDACI Rank": "14983",
        "IDACI Decile": "5",
        "IDACI Score": "0.14",
        "IDAOPI Rank": "14267",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.149",
    },
    {
        "Postcode": "BS1 4AP",
        "Postcode Status": "Live",
        "LSOA code": "E01014540",
        "LSOA Name": "Bristol 032B E01014540",
        "Index of Multiple Deprivation Rank": "12154",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "21851",
        "Income Decile": "7",
        "Income Score": "0.068",
        "Employment Rank": "26159",
        "Employment Decile": "8",
        "Employment Score": "0.046",
        "Education and Skills Rank": "12672",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "16466",
        "Health and Disability Decile": "6",
        "Crime Rank": "1511",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "3350",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "5016",
        "Living Environment Decile": "2",
        "IDACI Rank": "6119",
        "IDACI Decile": "2",
        "IDACI Score": "0.264",
        "IDAOPI Rank": "11842",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.175",
    },
    {
        "Postcode": "L1 3BG",
        "Postcode Status": "Live",
        "LSOA code": "E01033756",
        "LSOA Name": "Liverpool 061C E01033756",
        "Index of Multiple Deprivation Rank": "18895",
        "Index of Multiple Deprivation Decile": "6",
        "Income Rank": "31734",
        "Income Decile": "10",
        "Income Score": "0.024",
        "Employment Rank": "32180",
        "Employment Decile": "10",
        "Employment Score": "0.021",
        "Education and Skills Rank": "30430",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "11605",
        "Health and Disability Decile": "4",
        "Crime Rank": "1327",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "11918",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "7973",
        "Living Environment Decile": "3",
        "IDACI Rank": "29997",
        "IDACI Decile": "10",
        "IDACI Score": "0.035",
        "IDAOPI Rank": "17486",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.119",
    },
    {
        "Postcode": "LE2 7LT",
        "Postcode Status": "Live",
        "LSOA code": "E01013649",
        "LSOA Name": "Leicester 030C E01013649",
        "Index of Multiple Deprivation Rank": "15931",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "20436",
        "Income Decile": "7",
        "Income Score": "0.075",
        "Employment Rank": "20334",
        "Employment Decile": "7",
        "Employment Score": "0.064",
        "Education and Skills Rank": "28746",
        "Education and Skills Decile": "9",
        "Health and Disability Rank": "9181",
        "Health and Disability Decile": "3",
        "Crime Rank": "3524",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "25205",
        "Barriers to Housing and Services Decile": "8",
        "Living Environment Rank": "4691",
        "Living Environment Decile": "2",
        "IDACI Rank": "23399",
        "IDACI Decile": "8",
        "IDACI Score": "0.073",
        "IDAOPI Rank": "15983",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.132",
    },
    {
        "Postcode": "NG1 6EE",
        "Postcode Status": "Live",
        "LSOA code": "E01032522",
        "LSOA Name": "Nottingham 028F E01032522",
        "Index of Multiple Deprivation Rank": "19832",
        "Index of Multiple Deprivation Decile": "7",
        "Income Rank": "32426",
        "Income Decile": "10",
        "Income Score": "0.018",
        "Employment Rank": "32352",
        "Employment Decile": "10",
        "Employment Score": "0.019",
        "Education and Skills Rank": "30809",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "25639",
        "Health and Disability Decile": "8",
        "Crime Rank": "12659",
        "Crime Decile": "4",
        "Barriers to Housing and Services Rank": "4259",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "935",
        "Living Environment Decile": "1",
        "IDACI Rank": "29056",
        "IDACI Decile": "9",
        "IDACI Score": "0.04",
        "IDAOPI Rank": "31492",
        "IDAOPI Decile": "10",
        "IDAOPI Score": "0.034",
    },
    {
        "Postcode": "DN1 2JA",
        "Postcode Status": "Live",
        "LSOA code": "E01007647",
        "LSOA Name": "Doncaster 019C E01007647",
        "Index of Multiple Deprivation Rank": "12236",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "13298",
        "Income Decile": "5",
        "Income Score": "0.123",
        "Employment Rank": "11491",
        "Employment Decile": "4",
        "Employment Score": "0.107",
        "Education and Skills Rank": "19485",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "8007",
        "Health and Disability Decile": "3",
        "Crime Rank": "4335",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "19159",
        "Barriers to Housing and Services Decile": "6",
        "Living Environment Rank": "14690",
        "Living Environment Decile": "5",
        "IDACI Rank": "16334",
        "IDACI Decile": "5",
        "IDACI Score": "0.127",
        "IDAOPI Rank": "12283",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.17",
    },
    {
        "Postcode": "PE1 5BA",
        "Postcode Status": "Live",
        "LSOA code": "E01015611",
        "LSOA Name": "Peterborough 013B E01015611",
        "Index of Multiple Deprivation Rank": "3813",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "4626",
        "Income Decile": "2",
        "Income Score": "0.238",
        "Employment Rank": "7452",
        "Employment Decile": "3",
        "Employment Score": "0.14",
        "Education and Skills Rank": "2021",
        "Education and Skills Decile": "1",
        "Health and Disability Rank": "7145",
        "Health and Disability Decile": "3",
        "Crime Rank": "1773",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "4783",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "12499",
        "Living Environment Decile": "4",
        "IDACI Rank": "4764",
        "IDACI Decile": "2",
        "IDACI Score": "0.292",
        "IDAOPI Rank": "2542",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.371",
    },
    {
        "Postcode": "CB2 1ND",
        "Postcode Status": "Live",
        "LSOA code": "E01018005",
        "LSOA Name": "Cambridge 012D E01018005",
        "Index of Multiple Deprivation Rank": "15434",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "17806",
        "Income Decile": "6",
        "Income Score": "0.091",
        "Employment Rank": "13811",
        "Employment Decile": "5",
        "Employment Score": "0.093",
        "Education and Skills Rank": "15646",
        "Education and Skills Decile": "5",
        "Health and Disability Rank": "17364",
        "Health and Disability Decile": "6",
        "Crime Rank": "24444",
        "Crime Decile": "8",
        "Barriers to Housing and Services Rank": "13179",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "3564",
        "Living Environment Decile": "2",
        "IDACI Rank": "23486",
        "IDACI Decile": "8",
        "IDACI Score": "0.073",
        "IDAOPI Rank": "20041",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.1",
    },
    {
        "Postcode": "CV1 2DS",
        "Postcode Status": "Live",
        "LSOA code": "E01009642",
        "LSOA Name": "Coventry 031C E01009642",
        "Index of Multiple Deprivation Rank": "13010",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "20857",
        "Income Decile": "7",
        "Income Score": "0.073",
        "Employment Rank": "27854",
        "Employment Decile": "9",
        "Employment Score": "0.04",
        "Education and Skills Rank": "10764",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "7410",
        "Health and Disability Decile": "3",
        "Crime Rank": "9531",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "5121",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "4134",
        "Living Environment Decile": "2",
        "IDACI Rank": "7480",
        "IDACI Decile": "3",
        "IDACI Score": "0.24",
        "IDAOPI Rank": "2639",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.366",
    },
    {
        "Postcode": "DE1 2BA",
        "Postcode Status": "Live",
        "LSOA code": "E01033166",
        "LSOA Name": "Derby 018F E01033166",
        "Index of Multiple Deprivation Rank": "1569",
        "Index of Multiple Deprivation Decile": "1",
        "Income Rank": "2601",
        "Income Decile": "1",
        "Income Score": "0.288",
        "Employment Rank": "1806",
        "Employment Decile": "1",
        "Employment Score": "0.233",
        "Education and Skills Rank": "1390",
        "Education and Skills Decile": "1",
        "Health and Disability Rank": "2259",
        "Health and Disability Decile": "1",
        "Crime Rank": "1834",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "8401",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "10742",
        "Living Environment Decile": "4",
        "IDACI Rank": "5999",
        "IDACI Decile": "2",
        "IDACI Score": "0.267",
        "IDAOPI Rank": "1526",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.419",
    },
    {
        "Postcode": "NR1 1JR",
        "Postcode Status": "Live",
        "LSOA code": "E01033439",
        "LSOA Name": "Norwich 014B E01033439",
        "Index of Multiple Deprivation Rank": "10498",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "13013",
        "Income Decile": "4",
        "Income Score": "0.126",
        "Employment Rank": "12645",
        "Employment Decile": "4",
        "Employment Score": "0.099",
        "Education and Skills Rank": "21063",
        "Education and Skills Decile": "7",
        "Health and Disability Rank": "6416",
        "Health and Disability Decile": "2",
        "Crime Rank": "9647",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "24759",
        "Barriers to Housing and Services Decile": "8",
        "Living Environment Rank": "1177",
        "Living Environment Decile": "1",
        "IDACI Rank": "13293",
        "IDACI Decile": "5",
        "IDACI Score": "0.158",
        "IDAOPI Rank": "9425",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.208",
    },
    {
        "Postcode": "IP1 1AE",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033125",
        "LSOA Name": "Ipswich 007G E01033125",
        "Index of Multiple Deprivation Rank": "5982",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "8196",
        "Income Decile": "3",
        "Income Score": "0.178",
        "Employment Rank": "7786",
        "Employment Decile": "3",
        "Employment Score": "0.137",
        "Education and Skills Rank": "11645",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "3077",
        "Health and Disability Decile": "1",
        "Crime Rank": "5398",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "5439",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "7959",
        "Living Environment Decile": "3",
        "IDACI Rank": "5465",
        "IDACI Decile": "2",
        "IDACI Score": "0.277",
        "IDAOPI Rank": "2410",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.376",
    },
    {
        "Postcode": "SO15 2NP",
        "Postcode Status": "Live",
        "LSOA code": "E01017136",
        "LSOA Name": "Southampton 023A E01017136",
        "Index of Multiple Deprivation Rank": "15117",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "27356",
        "Income Decile": "9",
        "Income Score": "0.045",
        "Employment Rank": "32089",
        "Employment Decile": "10",
        "Employment Score": "0.021",
        "Education and Skills Rank": "19619",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "7443",
        "Health and Disability Decile": "3",
        "Crime Rank": "551",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "19936",
        "Barriers to Housing and Services Decile": "7",
        "Living Environment Rank": "6191",
        "Living Environment Decile": "2",
        "IDACI Rank": "9299",
        "IDACI Decile": "3",
        "IDACI Score": "0.212",
        "IDAOPI Rank": "9333",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.21",
    },
    {
        "Postcode": "SP1 2DG",
        "Postcode Status": "Terminated",
        "LSOA code": "E01032022",
        "LSOA Name": "Wiltshire 058C E01032022",
        "Index of Multiple Deprivation Rank": "15295",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "20282",
        "Income Decile": "7",
        "Income Score": "0.076",
        "Employment Rank": "15417",
        "Employment Decile": "5",
        "Employment Score": "0.084",
        "Education and Skills Rank": "27514",
        "Education and Skills Decile": "9",
        "Health and Disability Rank": "12716",
        "Health and Disability Decile": "4",
        "Crime Rank": "3335",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "25605",
        "Barriers to Housing and Services Decile": "8",
        "Living Environment Rank": "4632",
        "Living Environment Decile": "2",
        "IDACI Rank": "28870",
        "IDACI Decile": "9",
        "IDACI Score": "0.041",
        "IDAOPI Rank": "19953",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.101",
    },
    {
        "Postcode": "GU1 3AJ",
        "Postcode Status": "Live",
        "LSOA code": "E01030455",
        "LSOA Name": "Guildford 013E E01030455",
        "Index of Multiple Deprivation Rank": "22325",
        "Index of Multiple Deprivation Decile": "7",
        "Income Rank": "20248",
        "Income Decile": "7",
        "Income Score": "0.076",
        "Employment Rank": "20265",
        "Employment Decile": "7",
        "Employment Score": "0.064",
        "Education and Skills Rank": "32291",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "25038",
        "Health and Disability Decile": "8",
        "Crime Rank": "13093",
        "Crime Decile": "4",
        "Barriers to Housing and Services Rank": "16551",
        "Barriers to Housing and Services Decile": "6",
        "Living Environment Rank": "9014",
        "Living Environment Decile": "3",
        "IDACI Rank": "19532",
        "IDACI Decile": "6",
        "IDACI Score": "0.099",
        "IDAOPI Rank": "18616",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.11",
    },
    {
        "Postcode": "RG1 1BA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033415",
        "LSOA Name": "Reading 011F E01033415",
        "Index of Multiple Deprivation Rank": "11038",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "15072",
        "Income Decile": "5",
        "Income Score": "0.109",
        "Employment Rank": "20518",
        "Employment Decile": "7",
        "Employment Score": "0.064",
        "Education and Skills Rank": "18891",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "7295",
        "Health and Disability Decile": "3",
        "Crime Rank": "4345",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "2000",
        "Barriers to Housing and Services Decile": "1",
        "Living Environment Rank": "11307",
        "Living Environment Decile": "4",
        "IDACI Rank": "19983",
        "IDACI Decile": "7",
        "IDACI Score": "0.096",
        "IDAOPI Rank": "339",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.554",
    },
    {
        "Postcode": "MK9 3BL",
        "Postcode Status": "Live",
        "LSOA code": "E01033499",
        "LSOA Name": "Milton Keynes 014E E01033499",
        "Index of Multiple Deprivation Rank": "4854",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "6971",
        "Income Decile": "3",
        "Income Score": "0.195",
        "Employment Rank": "5473",
        "Employment Decile": "2",
        "Employment Score": "0.163",
        "Education and Skills Rank": "10820",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "9816",
        "Health and Disability Decile": "3",
        "Crime Rank": "5928",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "53",
        "Barriers to Housing and Services Decile": "1",
        "Living Environment Rank": "14563",
        "Living Environment Decile": "5",
        "IDACI Rank": "8175",
        "IDACI Decile": "3",
        "IDACI Score": "0.229",
        "IDAOPI Rank": "8979",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.215",
    },
    {
        "Postcode": "HP1 1DN",
        "Postcode Status": "Live",
        "LSOA code": "E01023400",
        "LSOA Name": "Dacorum 015E E01023400",
        "Index of Multiple Deprivation Rank": "14119",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "13388",
        "Income Decile": "5",
        "Income Score": "0.123",
        "Employment Rank": "12676",
        "Employment Decile": "4",
        "Employment Score": "0.099",
        "Education and Skills Rank": "17384",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "14286",
        "Health and Disability Decile": "5",
        "Crime Rank": "6873",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "12666",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "18791",
        "Living Environment Decile": "6",
        "IDACI Rank": "17588",
        "IDACI Decile": "6",
        "IDACI Score": "0.115",
        "IDAOPI Rank": "12809",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.164",
    },
    {
        "Postcode": "AL1 3AG",
        "Postcode Status": "Live",
        "LSOA code": "E01023729",
        "LSOA Name": "St Albans 012D E01023729",
        "Index of Multiple Deprivation Rank": "27026",
        "Index of Multiple Deprivation Decile": "9",
        "Income Rank": "21996",
        "Income Decile": "7",
        "Income Score": "0.068",
        "Employment Rank": "23691",
        "Employment Decile": "8",
        "Employment Score": "0.053",
        "Education and Skills Rank": "31810",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "30948",
        "Health and Disability Decile": "10",
        "Crime Rank": "20011",
        "Crime Decile": "7",
        "Barriers to Housing and Services Rank": "15051",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "17102",
        "Living Environment Decile": "6",
        "IDACI Rank": "21996",
        "IDACI Decile": "7",
        "IDACI Score": "0.082",
        "IDAOPI Rank": "16248",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.13",
    },
    {
        "Postcode": "CM1 1BY",
        "Postcode Status": "Live",
        "LSOA code": "E01021574",
        "LSOA Name": "Chelmsford 010A E01021574",
        "Index of Multiple Deprivation Rank": "24690",
        "Index of Multiple Deprivation Decile": "8",
        "Income Rank": "23502",
        "Income Decile": "8",
        "Income Score": "0.061",
        "Employment Rank": "25800",
        "Employment Decile": "8",
        "Employment Score": "0.047",
        "Education and Skills Rank": "24054",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "27516",
        "Health and Disability Decile": "9",
        "Crime Rank": "20721",
        "Crime Decile": "7",
        "Barriers to Housing and Services Rank": "7679",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "16591",
        "Living Environment Decile": "6",
        "IDACI Rank": "16677",
        "IDACI Decile": "6",
        "IDACI Score": "0.124",
        "IDAOPI Rank": "16080",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.131",
    },
    {
        "Postcode": "CO1 1AU",
        "Postcode Status": "Live",
        "LSOA code": "E01021647",
        "LSOA Name": "Colchester 007B E01021647",
        "Index of Multiple Deprivation Rank": "17505",
        "Index of Multiple Deprivation Decile": "6",
        "Income Rank": "20367",
        "Income Decile": "7",
        "Income Score": "0.076",
        "Employment Rank": "21017",
        "Employment Decile": "7",
        "Employment Score": "0.062",
        "Education and Skills Rank": "25137",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "23586",
        "Health and Disability Decile": "8",
        "Crime Rank": "3184",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "7091",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "12698",
        "Living Environment Decile": "4",
        "IDACI Rank": "16758",
        "IDACI Decile": "6",
        "IDACI Score": "0.123",
        "IDAOPI Rank": "26528",
        "IDAOPI Decile": "9",
        "IDAOPI Score": "0.063",
    },
    {
        "Postcode": "SS0 7AG",
        "Postcode Status": "Live",
        "LSOA code": "E01015899",
        "LSOA Name": "Southend-on-Sea 010E E01015899",
        "Index of Multiple Deprivation Rank": "7007",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "7397",
        "Income Decile": "3",
        "Income Score": "0.189",
        "Employment Rank": "6621",
        "Employment Decile": "3",
        "Employment Score": "0.149",
        "Education and Skills Rank": "6802",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "11878",
        "Health and Disability Decile": "4",
        "Crime Rank": "5053",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "17434",
        "Barriers to Housing and Services Decile": "6",
        "Living Environment Rank": "5603",
        "Living Environment Decile": "2",
        "IDACI Rank": "7249",
        "IDACI Decile": "3",
        "IDACI Score": "0.244",
        "IDAOPI Rank": "10395",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.194",
    },
    {
        "Postcode": "ME14 1BQ",
        "Postcode Status": "Live",
        "LSOA code": "E01033090",
        "LSOA Name": "Maidstone 004F E01033090",
        "Index of Multiple Deprivation Rank": "6699",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "8166",
        "Income Decile": "3",
        "Income Score": "0.178",
        "Employment Rank": "9027",
        "Employment Decile": "3",
        "Employment Score": "0.125",
        "Education and Skills Rank": "13119",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "10785",
        "Health and Disability Decile": "4",
        "Crime Rank": "1929",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "9242",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "2873",
        "Living Environment Decile": "1",
        "IDACI Rank": "10573",
        "IDACI Decile": "4",
        "IDACI Score": "0.193",
        "IDAOPI Rank": "5683",
        "IDAOPI Decile": "2",
        "IDAOPI Score": "0.276",
    },
    {
        "Postcode": "TN1 1DD",
        "Postcode Status": "Live",
        "LSOA code": "E01024819",
        "LSOA Name": "Tunbridge Wells 012D E01024819",
        "Index of Multiple Deprivation Rank": "30349",
        "Index of Multiple Deprivation Decile": "10",
        "Income Rank": "25312",
        "Income Decile": "8",
        "Income Score": "0.053",
        "Employment Rank": "26999",
        "Employment Decile": "9",
        "Employment Score": "0.043",
        "Education and Skills Rank": "32138",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "31366",
        "Health and Disability Decile": "10",
        "Crime Rank": "27060",
        "Crime Decile": "9",
        "Barriers to Housing and Services Rank": "25942",
        "Barriers to Housing and Services Decile": "8",
        "Living Environment Rank": "14388",
        "Living Environment Decile": "5",
        "IDACI Rank": "24590",
        "IDACI Decile": "8",
        "IDACI Score": "0.066",
        "IDAOPI Rank": "21590",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.09",
    },
    {
        "Postcode": "RH1 1AT",
        "Postcode Status": "Live",
        "LSOA code": "E01030612",
        "LSOA Name": "Reigate and Banstead 011C E01030612",
        "Index of Multiple Deprivation Rank": "24689",
        "Index of Multiple Deprivation Decile": "8",
        "Income Rank": "25964",
        "Income Decile": "8",
        "Income Score": "0.051",
        "Employment Rank": "29042",
        "Employment Decile": "9",
        "Employment Score": "0.036",
        "Education and Skills Rank": "27904",
        "Education and Skills Decile": "9",
        "Health and Disability Rank": "21779",
        "Health and Disability Decile": "7",
        "Crime Rank": "17112",
        "Crime Decile": "6",
        "Barriers to Housing and Services Rank": "4583",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "21871",
        "Living Environment Decile": "7",
        "IDACI Rank": "24768",
        "IDACI Decile": "8",
        "IDACI Score": "0.065",
        "IDAOPI Rank": "17234",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.121",
    },
    {
        "Postcode": "PO1 3AL",
        "Postcode Status": "Live",
        "LSOA code": "E01017034",
        "LSOA Name": "Portsmouth 016D E01017034",
        "Index of Multiple Deprivation Rank": "12150",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "11447",
        "Income Decile": "4",
        "Income Score": "0.14",
        "Employment Rank": "19132",
        "Employment Decile": "6",
        "Employment Score": "0.069",
        "Education and Skills Rank": "6753",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "7844",
        "Health and Disability Decile": "3",
        "Crime Rank": "9568",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "12914",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "18976",
        "Living Environment Decile": "6",
        "IDACI Rank": "2137",
        "IDACI Decile": "1",
        "IDACI Score": "0.368",
        "IDAOPI Rank": "2817",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.359",
    },
    {
        "Postcode": "BN1 1AB",
        "Postcode Status": "Live",
        "LSOA code": "E01016952",
        "LSOA Name": "Brighton and Hove 027A E01016952",
        "Index of Multiple Deprivation Rank": "8856",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "18958",
        "Income Decile": "6",
        "Income Score": "0.084",
        "Employment Rank": "19331",
        "Employment Decile": "6",
        "Employment Score": "0.068",
        "Education and Skills Rank": "17737",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "14165",
        "Health and Disability Decile": "5",
        "Crime Rank": "130",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "5842",
        "Barriers to Housing and Services Decile": "2",
        "Living Environment Rank": "1483",
        "Living Environment Decile": "1",
        "IDACI Rank": "15548",
        "IDACI Decile": "5",
        "IDACI Score": "0.134",
        "IDAOPI Rank": "6717",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.254",
    },
    {
        "Postcode": "EX1 1AF",
        "Postcode Status": "Live",
        "LSOA code": "E01020016",
        "LSOA Name": "Exeter 008C E01020016",
        "Index of Multiple Deprivation Rank": "5374",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "6896",
        "Income Decile": "3",
        "Income Score": "0.196",
        "Employment Rank": "4362",
        "Employment Decile": "2",
        "Employment Score": "0.179",
        "Education and Skills Rank": "9381",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "2557",
        "Health and Disability Decile": "1",
        "Crime Rank": "6170",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "13762",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "12172",
        "Living Environment Decile": "4",
        "IDACI Rank": "7433",
        "IDACI Decile": "3",
        "IDACI Score": "0.241",
        "IDAOPI Rank": "6082",
        "IDAOPI Decile": "2",
        "IDAOPI Score": "0.267",
    },
    {
        "Postcode": "PL1 1AL",
        "Postcode Status": "**UNMATCHED**",
        "LSOA code": "",
        "LSOA Name": "",
        "Index of Multiple Deprivation Rank": "",
        "Index of Multiple Deprivation Decile": "",
        "Income Rank": "",
        "Income Decile": "",
        "Income Score": "",
        "Employment Rank": "",
        "Employment Decile": "",
        "Employment Score": "",
        "Education and Skills Rank": "",
        "Education and Skills Decile": "",
        "Health and Disability Rank": "",
        "Health and Disability Decile": "",
        "Crime Rank": "",
        "Crime Decile": "",
        "Barriers to Housing and Services Rank": "",
        "Barriers to Housing and Services Decile": "",
        "Living Environment Rank": "",
        "Living Environment Decile": "",
        "IDACI Rank": "",
        "IDACI Decile": "",
        "IDACI Score": "",
        "IDAOPI Rank": "",
        "IDAOPI Decile": "",
        "IDAOPI Score": "",
    },
    {
        "Postcode": "TR1 1AA",
        "Postcode Status": "Live",
        "LSOA code": "E01018807",
        "LSOA Name": "Cornwall 044A E01018807",
        "Index of Multiple Deprivation Rank": "18766",
        "Index of Multiple Deprivation Decile": "6",
        "Income Rank": "17804",
        "Income Decile": "6",
        "Income Score": "0.091",
        "Employment Rank": "14012",
        "Employment Decile": "5",
        "Employment Score": "0.092",
        "Education and Skills Rank": "26111",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "18069",
        "Health and Disability Decile": "6",
        "Crime Rank": "24412",
        "Crime Decile": "8",
        "Barriers to Housing and Services Rank": "13245",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "9149",
        "Living Environment Decile": "3",
        "IDACI Rank": "16673",
        "IDACI Decile": "6",
        "IDACI Score": "0.124",
        "IDAOPI Rank": "19082",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.107",
    },
    {
        "Postcode": "TA1 1DT",
        "Postcode Status": "Live",
        "LSOA code": "E01029288",
        "LSOA Name": "Taunton Deane 007C E01029288",
        "Index of Multiple Deprivation Rank": "18758",
        "Index of Multiple Deprivation Decile": "6",
        "Income Rank": "19972",
        "Income Decile": "7",
        "Income Score": "0.078",
        "Employment Rank": "15121",
        "Employment Decile": "5",
        "Employment Score": "0.086",
        "Education and Skills Rank": "23315",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "19462",
        "Health and Disability Decile": "6",
        "Crime Rank": "14716",
        "Crime Decile": "5",
        "Barriers to Housing and Services Rank": "10633",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "12606",
        "Living Environment Decile": "4",
        "IDACI Rank": "25916",
        "IDACI Decile": "8",
        "IDACI Score": "0.058",
        "IDAOPI Rank": "22717",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.084",
    },
    {
        "Postcode": "BA1 1AL",
        "Postcode Status": "Live",
        "LSOA code": "E01014407",
        "LSOA Name": "Bath and North East Somerset 009C E01014407",
        "Index of Multiple Deprivation Rank": "9836",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "9830",
        "Income Decile": "3",
        "Income Score": "0.157",
        "Employment Rank": "11754",
        "Employment Decile": "4",
        "Employment Score": "0.105",
        "Education and Skills Rank": "13427",
        "Education and Skills Decile": "5",
        "Health and Disability Rank": "7603",
        "Health and Disability Decile": "3",
        "Crime Rank": "7452",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "21774",
        "Barriers to Housing and Services Decile": "7",
        "Living Environment Rank": "4170",
        "Living Environment Decile": "2",
        "IDACI Rank": "3509",
        "IDACI Decile": "2",
        "IDACI Score": "0.323",
        "IDAOPI Rank": "4996",
        "IDAOPI Decile": "2",
        "IDAOPI Score": "0.293",
    },
    {
        "Postcode": "GL1 1AH",
        "Postcode Status": "Live",
        "LSOA code": "E01022312",
        "LSOA Name": "Gloucester 002D E01022312",
        "Index of Multiple Deprivation Rank": "15803",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "16042",
        "Income Decile": "5",
        "Income Score": "0.102",
        "Employment Rank": "13989",
        "Employment Decile": "5",
        "Employment Score": "0.092",
        "Education and Skills Rank": "24637",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "8326",
        "Health and Disability Decile": "3",
        "Crime Rank": "16682",
        "Crime Decile": "6",
        "Barriers to Housing and Services Rank": "7781",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "20678",
        "Living Environment Decile": "7",
        "IDACI Rank": "17988",
        "IDACI Decile": "6",
        "IDACI Score": "0.112",
        "IDAOPI Rank": "13999",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.151",
    },
    {
        "Postcode": "WR1 1DU",
        "Postcode Status": "Live",
        "LSOA code": "E01032282",
        "LSOA Name": "Worcester 007C E01032282",
        "Index of Multiple Deprivation Rank": "10877",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "15715",
        "Income Decile": "5",
        "Income Score": "0.104",
        "Employment Rank": "18827",
        "Employment Decile": "6",
        "Employment Score": "0.07",
        "Education and Skills Rank": "9152",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "11405",
        "Health and Disability Decile": "4",
        "Crime Rank": "7091",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "14350",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "1363",
        "Living Environment Decile": "1",
        "IDACI Rank": "13872",
        "IDACI Decile": "5",
        "IDACI Score": "0.152",
        "IDAOPI Rank": "7484",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.24",
    },
    {
        "Postcode": "ST1 1AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01014287",
        "LSOA Name": "Stoke-on-Trent 015D E01014287",
        "Index of Multiple Deprivation Rank": "447",
        "Index of Multiple Deprivation Decile": "1",
        "Income Rank": "1246",
        "Income Decile": "1",
        "Income Score": "0.338",
        "Employment Rank": "509",
        "Employment Decile": "1",
        "Employment Score": "0.294",
        "Education and Skills Rank": "1740",
        "Education and Skills Decile": "1",
        "Health and Disability Rank": "152",
        "Health and Disability Decile": "1",
        "Crime Rank": "475",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "15790",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "12819",
        "Living Environment Decile": "4",
        "IDACI Rank": "2272",
        "IDACI Decile": "1",
        "IDACI Score": "0.363",
        "IDAOPI Rank": "2123",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.388",
    },
    {
        "Postcode": "SY1 1AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01028946",
        "LSOA Name": "Shropshire 019A E01028946",
        "Index of Multiple Deprivation Rank": "16829",
        "Index of Multiple Deprivation Decile": "6",
        "Income Rank": "19800",
        "Income Decile": "7",
        "Income Score": "0.079",
        "Employment Rank": "21118",
        "Employment Decile": "7",
        "Employment Score": "0.061",
        "Education and Skills Rank": "24297",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "16374",
        "Health and Disability Decile": "5",
        "Crime Rank": "7691",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "17790",
        "Barriers to Housing and Services Decile": "6",
        "Living Environment Rank": "2768",
        "Living Environment Decile": "1",
        "IDACI Rank": "21258",
        "IDACI Decile": "7",
        "IDACI Score": "0.087",
        "IDAOPI Rank": "18815",
        "IDAOPI Decile": "6",
        "IDAOPI Score": "0.109",
    },
    {
        "Postcode": "TF1 1AA",
        "Postcode Status": "Live",
        "LSOA code": "E01014145",
        "LSOA Name": "Telford and Wrekin 012D E01014145",
        "Index of Multiple Deprivation Rank": "7383",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "6824",
        "Income Decile": "3",
        "Income Score": "0.197",
        "Employment Rank": "5791",
        "Employment Decile": "2",
        "Employment Score": "0.159",
        "Education and Skills Rank": "10084",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "5151",
        "Health and Disability Decile": "2",
        "Crime Rank": "8126",
        "Crime Decile": "3",
        "Barriers to Housing and Services Rank": "19913",
        "Barriers to Housing and Services Decile": "7",
        "Living Environment Rank": "14609",
        "Living Environment Decile": "5",
        "IDACI Rank": "8979",
        "IDACI Decile": "3",
        "IDACI Score": "0.217",
        "IDAOPI Rank": "8326",
        "IDAOPI Decile": "3",
        "IDAOPI Score": "0.225",
    },
    {
        "Postcode": "WA1 1BA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033300",
        "LSOA Name": "Warrington 018F E01033300",
        "Index of Multiple Deprivation Rank": "3956",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "5723",
        "Income Decile": "2",
        "Income Score": "0.217",
        "Employment Rank": "3815",
        "Employment Decile": "2",
        "Employment Score": "0.188",
        "Education and Skills Rank": "11517",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "1371",
        "Health and Disability Decile": "1",
        "Crime Rank": "3062",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "12534",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "9402",
        "Living Environment Decile": "3",
        "IDACI Rank": "8060",
        "IDACI Decile": "3",
        "IDACI Score": "0.231",
        "IDAOPI Rank": "2456",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.374",
    },
    {
        "Postcode": "CH1 1BA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01018329",
        "LSOA Name": "Cheshire West and Chester 034C E01018329",
        "Index of Multiple Deprivation Rank": "11969",
        "Index of Multiple Deprivation Decile": "4",
        "Income Rank": "18422",
        "Income Decile": "6",
        "Income Score": "0.087",
        "Employment Rank": "18349",
        "Employment Decile": "6",
        "Employment Score": "0.072",
        "Education and Skills Rank": "23201",
        "Education and Skills Decile": "8",
        "Health and Disability Rank": "6211",
        "Health and Disability Decile": "2",
        "Crime Rank": "13938",
        "Crime Decile": "5",
        "Barriers to Housing and Services Rank": "15315",
        "Barriers to Housing and Services Decile": "5",
        "Living Environment Rank": "451",
        "Living Environment Decile": "1",
        "IDACI Rank": "16855",
        "IDACI Decile": "6",
        "IDACI Score": "0.122",
        "IDAOPI Rank": "11416",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.181",
    },
    {
        "Postcode": "BB1 1BB",
        "Postcode Status": "Live",
        "LSOA code": "E01012629",
        "LSOA Name": "Blackburn with Darwen 006A E01012629",
        "Index of Multiple Deprivation Rank": "4445",
        "Index of Multiple Deprivation Decile": "2",
        "Income Rank": "7014",
        "Income Decile": "3",
        "Income Score": "0.194",
        "Employment Rank": "3456",
        "Employment Decile": "2",
        "Employment Score": "0.194",
        "Education and Skills Rank": "11758",
        "Education and Skills Decile": "4",
        "Health and Disability Rank": "1848",
        "Health and Disability Decile": "1",
        "Crime Rank": "1807",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "28917",
        "Barriers to Housing and Services Decile": "9",
        "Living Environment Rank": "7429",
        "Living Environment Decile": "3",
        "IDACI Rank": "11869",
        "IDACI Decile": "4",
        "IDACI Score": "0.176",
        "IDAOPI Rank": "13577",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.156",
    },
    {
        "Postcode": "PR1 1AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01025290",
        "LSOA Name": "Preston 017B E01025290",
        "Index of Multiple Deprivation Rank": "2694",
        "Index of Multiple Deprivation Decile": "1",
        "Income Rank": "3697",
        "Income Decile": "2",
        "Income Score": "0.258",
        "Employment Rank": "2849",
        "Employment Decile": "1",
        "Employment Score": "0.206",
        "Education and Skills Rank": "8599",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "906",
        "Health and Disability Decile": "1",
        "Crime Rank": "10085",
        "Crime Decile": "4",
        "Barriers to Housing and Services Rank": "22865",
        "Barriers to Housing and Services Decile": "7",
        "Living Environment Rank": "996",
        "Living Environment Decile": "1",
        "IDACI Rank": "4276",
        "IDACI Decile": "2",
        "IDACI Score": "0.302",
        "IDAOPI Rank": "979",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.46",
    },
    {
        "Postcode": "FY1 1AQ",
        "Postcode Status": "Live",
        "LSOA code": "E01012681",
        "LSOA Name": "Blackpool 006A E01012681",
        "Index of Multiple Deprivation Rank": "3",
        "Index of Multiple Deprivation Decile": "1",
        "Income Rank": "39",
        "Income Decile": "1",
        "Income Score": "0.499",
        "Employment Rank": "6",
        "Employment Decile": "1",
        "Employment Score": "0.464",
        "Education and Skills Rank": "247",
        "Education and Skills Decile": "1",
        "Health and Disability Rank": "1",
        "Health and Disability Decile": "1",
        "Crime Rank": "1",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "19540",
        "Barriers to Housing and Services Decile": "6",
        "Living Environment Rank": "392",
        "Living Environment Decile": "1",
        "IDACI Rank": "85",
        "IDACI Decile": "1",
        "IDACI Score": "0.567",
        "IDAOPI Rank": "1210",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.44",
    },
    {
        "Postcode": "BD1 1AH",
        "Postcode Status": "Live",
        "LSOA code": "E01033690",
        "LSOA Name": "Bradford 039G E01033690",
        "Index of Multiple Deprivation Rank": "6594",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "17365",
        "Income Decile": "6",
        "Income Score": "0.093",
        "Employment Rank": "17882",
        "Employment Decile": "6",
        "Employment Score": "0.074",
        "Education and Skills Rank": "7131",
        "Education and Skills Decile": "3",
        "Health and Disability Rank": "9407",
        "Health and Disability Decile": "3",
        "Crime Rank": "1001",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "7895",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "120",
        "Living Environment Decile": "1",
        "IDACI Rank": "15610",
        "IDACI Decile": "5",
        "IDACI Score": "0.134",
        "IDAOPI Rank": "5842",
        "IDAOPI Decile": "2",
        "IDAOPI Score": "0.272",
    },
    {
        "Postcode": "LS1 1BA",
        "Postcode Status": "Live",
        "LSOA code": "E01033008",
        "LSOA Name": "Leeds 111A E01033008",
        "Index of Multiple Deprivation Rank": "13916",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "32753",
        "Income Decile": "10",
        "Income Score": "0.011",
        "Employment Rank": "32755",
        "Employment Decile": "10",
        "Employment Score": "0.01",
        "Education and Skills Rank": "16662",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "5291",
        "Health and Disability Decile": "2",
        "Crime Rank": "18524",
        "Crime Decile": "6",
        "Barriers to Housing and Services Rank": "9372",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "35",
        "Living Environment Decile": "1",
        "IDACI Rank": "10373",
        "IDACI Decile": "4",
        "IDACI Score": "0.196",
        "IDAOPI Rank": "11610",
        "IDAOPI Decile": "4",
        "IDAOPI Score": "0.178",
    },
    {
        "Postcode": "S1 2AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033268",
        "LSOA Name": "Sheffield 075G E01033268",
        "Index of Multiple Deprivation Rank": "8740",
        "Index of Multiple Deprivation Decile": "3",
        "Income Rank": "12638",
        "Income Decile": "4",
        "Income Score": "0.129",
        "Employment Rank": "15152",
        "Employment Decile": "5",
        "Employment Score": "0.085",
        "Education and Skills Rank": "6348",
        "Education and Skills Decile": "2",
        "Health and Disability Rank": "6610",
        "Health and Disability Decile": "3",
        "Crime Rank": "1752",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "11708",
        "Barriers to Housing and Services Decile": "4",
        "Living Environment Rank": "12450",
        "Living Environment Decile": "4",
        "IDACI Rank": "18173",
        "IDACI Decile": "6",
        "IDACI Score": "0.11",
        "IDAOPI Rank": "2061",
        "IDAOPI Decile": "1",
        "IDAOPI Score": "0.391",
    },
    {
        "Postcode": "NE1 1AE",
        "Postcode Status": "Live",
        "LSOA code": "E01033543",
        "LSOA Name": "Newcastle upon Tyne 024G E01033543",
        "Index of Multiple Deprivation Rank": "13862",
        "Index of Multiple Deprivation Decile": "5",
        "Income Rank": "31738",
        "Income Decile": "10",
        "Income Score": "0.024",
        "Employment Rank": "31885",
        "Employment Decile": "10",
        "Employment Score": "0.023",
        "Education and Skills Rank": "17880",
        "Education and Skills Decile": "6",
        "Health and Disability Rank": "9072",
        "Health and Disability Decile": "3",
        "Crime Rank": "474",
        "Crime Decile": "1",
        "Barriers to Housing and Services Rank": "9169",
        "Barriers to Housing and Services Decile": "3",
        "Living Environment Rank": "4374",
        "Living Environment Decile": "2",
        "IDACI Rank": "32114",
        "IDACI Decile": "10",
        "IDACI Score": "0.018",
        "IDAOPI Rank": "13805",
        "IDAOPI Decile": "5",
        "IDAOPI Score": "0.153",
    },
    {
        "Postcode": "DH1 1AA",
        "Postcode Status": "Terminated",
        "LSOA code": "E01033164",
        "LSOA Name": "County Durham 030D E01033164",
        "Index of Multiple Deprivation Rank": "26229",
        "Index of Multiple Deprivation Decile": "8",
        "Income Rank": "32588",
        "Income Decile": "10",
        "Income Score": "0.015",
        "Employment Rank": "32754",
        "Employment Decile": "10",
        "Employment Score": "0.01",
        "Education and Skills Rank": "31963",
        "Education and Skills Decile": "10",
        "Health and Disability Rank": "16227",
        "Health and Disability Decile": "5",
        "Crime Rank": "5641",
        "Crime Decile": "2",
        "Barriers to Housing and Services Rank": "22236",
        "Barriers to Housing and Services Decile": "7",
        "Living Environment Rank": "13208",
        "Living Environment Decile": "5",
        "IDACI Rank": "23895",
        "IDACI Decile": "8",
        "IDACI Score": "0.07",
        "IDAOPI Rank": "21718",
        "IDAOPI Decile": "7",
        "IDAOPI Score": "0.089",
    },
    {
        "Postcode": "TS1 1AP",
        "Postcode Status": "**UNMATCHED**",
        "LSOA code": "",
        "LSOA Name": "",
        "Index of Multiple Deprivation Rank": "",
        "Index of Multiple Deprivation Decile": "",
        "Income Rank": "",
        "Income Decile": "",
        "Income Score": "",
        "Employment Rank": "",
        "Employment Decile": "",
        "Employment Score": "",
        "Education and Skills Rank": "",
        "Education and Skills Decile": "",
        "Health and Disability Rank": "",
        "Health and Disability Decile": "",
        "Crime Rank": "",
        "Crime Decile": "",
        "Barriers to Housing and Services Rank": "",
        "Barriers to Housing and Services Decile": "",
        "Living Environment Rank": "",
        "Living Environment Decile": "",
        "IDACI Rank": "",
        "IDACI Decile": "",
        "IDACI Score": "",
        "IDAOPI Rank": "",
        "IDAOPI Decile": "",
        "IDAOPI Score": "",
    },
]


@pytest.mark.django_db
class TestIndicesOfMultipleDeprivation2019:
    """Tests for the indices_of_multiple_deprivation endpoint using 2019 English IMD data."""

    def test_valid_postcode_returns_imd_data(self, api_client):
        """Test that a valid postcode returns IMD data for 2019."""
        # Use SE1 7PB which is a live postcode in the test data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        # Check key fields are present
        assert "imd_rank" in data
        assert "imd_decile" in data
        assert "lsoa" in data

    def test_imd_rank_matches_expected_2019(self, api_client):
        """Test that IMD rank matches expected value from 2019 dataset."""
        # SE1 7PB has IMD Rank 21865 in 2019 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_rank"] == 21865

    def test_imd_decile_matches_expected_2019(self, api_client):
        """Test that IMD decile matches expected value from 2019 dataset."""
        # SE1 7PB has IMD Decile 7 in 2019 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_decile"] == 7

    def test_income_rank_matches_expected_2019(self, api_client):
        """Test that income domain rank matches expected value from 2019 dataset."""
        # M1 5AL has Income Rank 28159 in 2019 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "M1 5AL", "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["income_rank"] == 28159

    def test_high_deprivation_postcode_2019(self, api_client):
        """Test a high deprivation postcode (low rank) from 2019 dataset."""
        # M1 5AL has IMD Rank 8998 and Decile 3 in 2019 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "M1 5AL", "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_rank"] == 8998
        assert data["imd_decile"] == 3

    def test_missing_postcode_returns_error(self, api_client):
        """Test that missing postcode returns an error."""
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"year": 2019},
        )
        assert response.status_code == 400

    def test_invalid_postcode_returns_error(self, api_client):
        """Test that an invalid postcode returns an error."""
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "INVALID", "year": 2019},
        )
        assert response.status_code == 400

    def test_default_year_is_2019(self, api_client):
        """Test that the default year is 2019 when not specified."""
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB"},
        )
        assert response.status_code == 200
        data = response.json()
        # Should return 2019 data by default
        assert data["imd_rank"] == 21865


@pytest.mark.django_db
class TestIndicesOfMultipleDeprivation2025:
    """Tests for the indices_of_multiple_deprivation endpoint using 2025 English IMD data."""

    def test_valid_postcode_returns_imd_data_2025(self, api_client):
        """Test that a valid postcode returns IMD data for 2025."""
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert "imd_rank" in data
        assert "imd_decile" in data
        assert "lsoa" in data

    def test_imd_rank_matches_expected_2025(self, api_client):
        """Test that IMD rank matches expected value from 2025 dataset."""
        # SE1 7PB has IMD Rank 23019 and Decile 7 in 2025 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_rank"] == 23019

    def test_imd_decile_matches_expected_2025(self, api_client):
        """Test that IMD decile matches expected value from 2025 dataset."""
        # SE1 7PB has Decile 7 in 2025 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_decile"] == 7

    def test_high_deprivation_postcode_2025(self, api_client):
        """Test a high deprivation postcode from 2025 dataset."""
        # FY1 1AQ (Blackpool) has IMD Rank 36 and Decile 1 in 2025 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "FY1 1AQ", "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_rank"] == 36
        assert data["imd_decile"] == 1

    def test_low_deprivation_postcode_2025(self, api_client):
        """Test a low deprivation postcode from 2025 dataset."""
        # NG1 6EE (Nottingham) has IMD Rank 29480 and Decile 9 in 2025 data
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "NG1 6EE", "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert data["imd_rank"] == 29480
        assert data["imd_decile"] == 9

    def test_2019_and_2025_return_different_ranks(self, api_client):
        """Test that 2019 and 2025 return different IMD ranks for the same postcode."""
        response_2019 = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "M1 5AL", "year": 2019},
        )
        response_2025 = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "M1 5AL", "year": 2025},
        )
        assert response_2019.status_code == 200
        assert response_2025.status_code == 200
        # 2019: rank 8998, 2025: rank 16860
        assert response_2019.json()["imd_rank"] == 8998
        assert response_2025.json()["imd_rank"] == 16860

    def test_invalid_year_returns_error(self, api_client):
        """Test that an invalid year returns an error."""
        response = api_client.get(
            INDICES_OF_MULTIPLE_DEPRIVATION_URL,
            {"postcode": "SE1 7PB", "year": 2020},
        )
        assert response.status_code == 400


@pytest.mark.django_db
class TestIndexOfMultipleDeprivationQuantile2019:
    """Tests for the index_of_multiple_deprivation_quantile endpoint using 2019 English IMD data."""

    def test_valid_postcode_returns_quantile_data(self, api_client):
        """Test that a valid postcode returns quantile data for 2019."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        assert "rank" in data["result"]
        assert "data_quantile" in data["result"]

    def test_decile_quantile_matches_expected_2019(self, api_client):
        """Test that decile (quantile=10) matches expected value from 2019 dataset."""
        # SE1 7PB has IMD Rank 21865 and Decile 7 in 2019 data
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["rank"] == 21865
        assert data["data_quantile"] == 7
        assert data["requested_quantile"] == 10
        assert data["requested_quantile_name"] == "decile"

    def test_quintile_calculation_2019(self, api_client):
        """Test quintile calculation for 2019 data."""
        # M1 5AL has IMD Rank 8998 which should be quintile 2 (rank 8998 / 32844 * 5 ≈ 1.37 → 2)
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "M1 5AL", "quantile": 5, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["rank"] == 8998
        assert data["requested_quantile"] == 5
        assert data["requested_quantile_name"] == "quintile"

    def test_quartile_calculation_2019(self, api_client):
        """Test quartile calculation for 2019 data."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 4, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["requested_quantile"] == 4
        assert data["requested_quantile_name"] == "quartile"

    def test_median_calculation_2019(self, api_client):
        """Test median (quantile=2) calculation for 2019 data."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 2, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["requested_quantile"] == 2
        assert data["requested_quantile_name"] == "median"

    def test_missing_quantile_returns_error(self, api_client):
        """Test that missing quantile parameter returns an error."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "year": 2019},
        )
        # Missing quantile should return 400
        assert response.status_code == 400

    def test_invalid_quantile_returns_error(self, api_client):
        """Test that an invalid quantile value returns a 400 error."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 15, "year": 2019},
        )
        # Quantile 15 is not valid - should return 400
        assert response.status_code == 400

    def test_country_is_england(self, api_client):
        """Test that country field is 'england' for English postcodes."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2019},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["country"] == "england"


@pytest.mark.django_db
class TestIndexOfMultipleDeprivationQuantile2025:
    """Tests for the index_of_multiple_deprivation_quantile endpoint using 2025 English IMD data."""

    def test_valid_postcode_returns_quantile_data_2025(self, api_client):
        """Test that a valid postcode returns quantile data for 2025."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        assert "rank" in data["result"]
        assert "data_quantile" in data["result"]

    def test_decile_quantile_matches_expected_2025(self, api_client):
        """Test that decile (quantile=10) matches expected value from 2025 dataset."""
        # SE1 7PB has IMD Rank 23019 and Decile 7 in 2025 data
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["rank"] == 23019
        assert data["data_quantile"] == 7

    def test_high_deprivation_decile_2025(self, api_client):
        """Test decile for a high deprivation postcode in 2025 data."""
        # FY1 1AQ (Blackpool) has IMD Rank 36 and Decile 1 in 2025 data
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "FY1 1AQ", "quantile": 10, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["rank"] == 36
        assert data["data_quantile"] == 1

    def test_low_deprivation_decile_2025(self, api_client):
        """Test decile for a low deprivation postcode in 2025 data."""
        # NG1 6EE has IMD Rank 29480 and Decile 9 in 2025 data
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "NG1 6EE", "quantile": 10, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["rank"] == 29480
        assert data["data_quantile"] == 9

    def test_quintile_calculation_2025(self, api_client):
        """Test quintile calculation for 2025 data."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "M1 5AL", "quantile": 5, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        # M1 5AL has IMD Rank 16860 in 2025 data
        assert data["rank"] == 16860
        assert data["requested_quantile"] == 5
        assert data["requested_quantile_name"] == "quintile"

    def test_2019_and_2025_return_different_quantiles(self, api_client):
        """Test that 2019 and 2025 return different quantile data for the same postcode."""
        response_2019 = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "M1 5AL", "quantile": 10, "year": 2019},
        )
        response_2025 = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "M1 5AL", "quantile": 10, "year": 2025},
        )
        assert response_2019.status_code == 200
        assert response_2025.status_code == 200
        # 2019: rank 8998 decile 3, 2025: rank 16860 decile 5
        data_2019 = response_2019.json()["result"]
        data_2025 = response_2025.json()["result"]
        assert data_2019["rank"] == 8998
        assert data_2019["data_quantile"] == 3
        assert data_2025["rank"] == 16860
        assert data_2025["data_quantile"] == 5

    def test_all_valid_quantiles_2025(self, api_client):
        """Test that all valid quantile values work for 2025 data."""
        valid_quantiles = [2, 3, 4, 5, 6, 7, 8, 10, 12, 18, 20]
        for quantile in valid_quantiles:
            response = api_client.get(
                INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
                {"postcode": "SE1 7PB", "quantile": quantile, "year": 2025},
            )
            assert response.status_code == 200, f"Failed for quantile {quantile}"
            data = response.json()["result"]
            assert data["requested_quantile"] == quantile

    def test_country_is_england_2025(self, api_client):
        """Test that country field is 'england' for English postcodes in 2025."""
        response = api_client.get(
            INDEX_OF_MULTIPLE_DEPRIVATION_QUANTILE_URL,
            {"postcode": "SE1 7PB", "quantile": 10, "year": 2025},
        )
        assert response.status_code == 200
        data = response.json()["result"]
        assert data["country"] == "england"
