"""
Mock postcodes.io API responses for testing.
This file was auto-generated by scripts/capture_postcode_responses.py

To regenerate:
    python scripts/capture_postcode_responses.py > tests/postcode_mock_data.py
"""

# Mock postcodes.io API responses for test postcodes
# Format: {postcode (no spaces, uppercase): response_data}
MOCK_POSTCODE_RESPONSES = {
    "AL13AG": {
        "status": 200,
        "result": {
            "postcode": "AL1 3AG",
            "country": "England",
            "lsoa": "St Albans 012D",
            "codes": {"lsoa": "E01023729"},
        },
    },
    "B11AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "B1 1AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "BA11AL": {
        "status": 200,
        "result": {
            "postcode": "BA1 1AL",
            "country": "England",
            "lsoa": "Bath and North East Somerset 009C",
            "codes": {"lsoa": "E01014407"},
        },
    },
    "BB11BB": {
        "status": 200,
        "result": {
            "postcode": "BB1 1BB",
            "country": "England",
            "lsoa": "Blackburn with Darwen 006A",
            "codes": {"lsoa": "E01012629"},
        },
    },
    "BD11AH": {
        "status": 200,
        "result": {
            "postcode": "BD1 1AH",
            "country": "England",
            "lsoa": "Bradford 039G",
            "codes": {"lsoa": "E01033690"},
        },
    },
    "BN11AB": {
        "status": 200,
        "result": {
            "postcode": "BN1 1AB",
            "country": "England",
            "lsoa": "Brighton and Hove 027A",
            "codes": {"lsoa": "E01016952"},
        },
    },
    "BS14AP": {
        "status": 200,
        "result": {
            "postcode": "BS1 4AP",
            "country": "England",
            "lsoa": "Bristol 032B",
            "codes": {"lsoa": "E01014540"},
        },
    },
    "BT356BP": {
        "status": 200,
        "result": {
            "postcode": "BT35 6BP",
            "country": "Northern Ireland",
            "lsoa": "Drumgullion 1",
            "codes": {"lsoa": "95VV15S1"},
        },
    },
    "BT43QL": {
        "status": 200,
        "result": {
            "postcode": "BT4 3QL",
            "country": "Northern Ireland",
            "lsoa": "Stormont 2",
            "codes": {"lsoa": "95GG41S2"},
        },
    },
    "BT487ET": {
        "status": 200,
        "result": {
            "postcode": "BT48 7ET",
            "country": "Northern Ireland",
            "lsoa": "Strand 1 Derry",
            "codes": {"lsoa": "95MM27S1"},
        },
    },
    "BT521PF": {
        "status": 200,
        "result": {
            "postcode": "BT52 1PF",
            "country": "Northern Ireland",
            "lsoa": "Central Coleraine",
            "codes": {"lsoa": "95JJ05W1"},
        },
    },
    "BT73FH": {
        "status": 200,
        "result": {
            "postcode": "BT7 3FH",
            "country": "Northern Ireland",
            "lsoa": "Rosetta 1",
            "codes": {"lsoa": "95GG38S1"},
        },
    },
    "CB21ND": {
        "status": 200,
        "result": {
            "postcode": "CB2 1ND",
            "country": "England",
            "lsoa": "Cambridge 012D",
            "codes": {"lsoa": "E01018005"},
        },
    },
    "CF103NQ": {
        "status": 200,
        "result": {
            "postcode": "CF10 3NQ",
            "country": "Wales",
            "lsoa": "Cardiff 032F",
            "codes": {"lsoa": "W01001939"},
        },
    },
    "CH11BA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "CH1 1BA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "CH65QX": {
        "status": 200,
        "result": {
            "postcode": "CH6 5QX",
            "country": "Wales",
            "lsoa": "Flintshire 005B",
            "codes": {"lsoa": "W01000291"},
        },
    },
    "CM11BY": {
        "status": 200,
        "result": {
            "postcode": "CM1 1BY",
            "country": "England",
            "lsoa": "Chelmsford 010A",
            "codes": {"lsoa": "E01021574"},
        },
    },
    "CO11AU": {
        "status": 200,
        "result": {
            "postcode": "CO1 1AU",
            "country": "England",
            "lsoa": "Colchester 007B",
            "codes": {"lsoa": "E01021647"},
        },
    },
    "CV12DS": {
        "status": 200,
        "result": {
            "postcode": "CV1 2DS",
            "country": "England",
            "lsoa": "Coventry 031C",
            "codes": {"lsoa": "E01009642"},
        },
    },
    "DE12BA": {
        "status": 200,
        "result": {
            "postcode": "DE1 2BA",
            "country": "England",
            "lsoa": "Derby 018F",
            "codes": {"lsoa": "E01033166"},
        },
    },
    "DH11AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "DH1 1AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "DN12JA": {
        "status": 200,
        "result": {
            "postcode": "DN1 2JA",
            "country": "England",
            "lsoa": "Doncaster 019C",
            "codes": {"lsoa": "E01007647"},
        },
    },
    "EH11AD": {
        "status": 200,
        "result": {
            "postcode": "EH1 1AD",
            "country": "Scotland",
            "lsoa": "Old Town, Princes Street and Leith Street - 01",
            "codes": {"lsoa": "S01008674"},
        },
    },
    "EX11AF": {
        "status": 200,
        "result": {
            "postcode": "EX1 1AF",
            "country": "England",
            "lsoa": "Exeter 008C",
            "codes": {"lsoa": "E01020016"},
        },
    },
    "FK11AA": {
        "status": 200,
        "result": {
            "postcode": "FK1 1AA",
            "country": "Scotland",
            "lsoa": "Falkirk - Grahamston - 03",
            "codes": {"lsoa": "S01009140"},
        },
    },
    "FY11AQ": {
        "status": 200,
        "result": {
            "postcode": "FY1 1AQ",
            "country": "England",
            "lsoa": "Blackpool 006A",
            "codes": {"lsoa": "E01012681"},
        },
    },
    "GL11AH": {
        "status": 200,
        "result": {
            "postcode": "GL1 1AH",
            "country": "England",
            "lsoa": "Gloucester 002D",
            "codes": {"lsoa": "E01022312"},
        },
    },
    "GU13AJ": {
        "status": 200,
        "result": {
            "postcode": "GU1 3AJ",
            "country": "England",
            "lsoa": "Guildford 013E",
            "codes": {"lsoa": "E01030455"},
        },
    },
    "HP11DN": {
        "status": 200,
        "result": {
            "postcode": "HP1 1DN",
            "country": "England",
            "lsoa": "Dacorum 015E",
            "codes": {"lsoa": "E01023400"},
        },
    },
    "IP11AE": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "IP1 1AE",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "KW14AA": {
        "status": 200,
        "result": {
            "postcode": "KW1 4AA",
            "country": "Scotland",
            "lsoa": "Wick North - 01",
            "codes": {"lsoa": "S01010782"},
        },
    },
    "L13BG": {
        "status": 200,
        "result": {
            "postcode": "L1 3BG",
            "country": "England",
            "lsoa": "Liverpool 061C",
            "codes": {"lsoa": "E01033756"},
        },
    },
    "LD15AB": {
        "status": 200,
        "result": {
            "postcode": "LD1 5AB",
            "country": "Wales",
            "lsoa": "Powys 013B",
            "codes": {"lsoa": "W01000455"},
        },
    },
    "LD30TP": {
        "status": 200,
        "result": {
            "postcode": "LD3 0TP",
            "country": "Wales",
            "lsoa": "Powys 020A",
            "codes": {"lsoa": "W01000440"},
        },
    },
    "LE27LT": {
        "status": 200,
        "result": {
            "postcode": "LE2 7LT",
            "country": "England",
            "lsoa": "Leicester 030C",
            "codes": {"lsoa": "E01013649"},
        },
    },
    "LS11BA": {
        "status": 200,
        "result": {
            "postcode": "LS1 1BA",
            "country": "England",
            "lsoa": "Leeds 111A",
            "codes": {"lsoa": "E01033008"},
        },
    },
    "M15AL": {
        "status": 200,
        "result": {
            "postcode": "M1 5AL",
            "country": "England",
            "lsoa": "Manchester 057C",
            "codes": {"lsoa": "E01033662"},
        },
    },
    "ME141BQ": {
        "status": 200,
        "result": {
            "postcode": "ME14 1BQ",
            "country": "England",
            "lsoa": "Maidstone 004F",
            "codes": {"lsoa": "E01033090"},
        },
    },
    "MK93BL": {
        "status": 200,
        "result": {
            "postcode": "MK9 3BL",
            "country": "England",
            "lsoa": "Milton Keynes 014E",
            "codes": {"lsoa": "E01033499"},
        },
    },
    "NE11AE": {
        "status": 200,
        "result": {
            "postcode": "NE1 1AE",
            "country": "England",
            "lsoa": "Newcastle upon Tyne 024G",
            "codes": {"lsoa": "E01033543"},
        },
    },
    "NG16EE": {
        "status": 200,
        "result": {
            "postcode": "NG1 6EE",
            "country": "England",
            "lsoa": "Nottingham 028F",
            "codes": {"lsoa": "E01032522"},
        },
    },
    "NR11JR": {
        "status": 200,
        "result": {
            "postcode": "NR1 1JR",
            "country": "England",
            "lsoa": "Norwich 014B",
            "codes": {"lsoa": "E01033439"},
        },
    },
    "PA11AD": {
        "status": 200,
        "result": {
            "postcode": "PA1 1AD",
            "country": "Scotland",
            "lsoa": "Paisley Central - 02",
            "codes": {"lsoa": "S01012127"},
        },
    },
    "PE15BA": {
        "status": 200,
        "result": {
            "postcode": "PE1 5BA",
            "country": "England",
            "lsoa": "Peterborough 013B",
            "codes": {"lsoa": "E01015611"},
        },
    },
    "PL11AL": None,
    "PO13AL": {
        "status": 200,
        "result": {
            "postcode": "PO1 3AL",
            "country": "England",
            "lsoa": "Portsmouth 016D",
            "codes": {"lsoa": "E01017034"},
        },
    },
    "PR11AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "PR1 1AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "RG11BA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "RG1 1BA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "RH11AT": {
        "status": 200,
        "result": {
            "postcode": "RH1 1AT",
            "country": "England",
            "lsoa": "Reigate and Banstead 011C",
            "codes": {"lsoa": "E01030612"},
        },
    },
    "S12AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "S1 2AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "SA11AA": {
        "status": 200,
        "result": {
            "postcode": "SA1 1AA",
            "country": "Wales",
            "lsoa": "Swansea 014D",
            "codes": {"lsoa": "W01000741"},
        },
    },
    "SE17PB": {
        "status": 200,
        "result": {
            "postcode": "SE1 7PB",
            "country": "England",
            "lsoa": "Lambeth 036A",
            "codes": {"lsoa": "E01003013"},
        },
    },
    "SO152NP": {
        "status": 200,
        "result": {
            "postcode": "SO15 2NP",
            "country": "England",
            "lsoa": "Southampton 023A",
            "codes": {"lsoa": "E01017136"},
        },
    },
    "SP12DG": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "SP1 2DG",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "SS07AG": {
        "status": 200,
        "result": {
            "postcode": "SS0 7AG",
            "country": "England",
            "lsoa": "Southend-on-Sea 010E",
            "codes": {"lsoa": "E01015899"},
        },
    },
    "ST11AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "ST1 1AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "SY11AA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "SY1 1AA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "TA11DT": {
        "status": 200,
        "result": {
            "postcode": "TA1 1DT",
            "country": "England",
            "lsoa": "Taunton Deane 007C",
            "codes": {"lsoa": "E01029288"},
        },
    },
    "TF11AA": {
        "status": 200,
        "result": {
            "postcode": "TF1 1AA",
            "country": "England",
            "lsoa": "Telford and Wrekin 012D",
            "codes": {"lsoa": "E01014145"},
        },
    },
    "TN11DD": {
        "status": 200,
        "result": {
            "postcode": "TN1 1DD",
            "country": "England",
            "lsoa": "Tunbridge Wells 012D",
            "codes": {"lsoa": "E01024819"},
        },
    },
    "TR11AA": {
        "status": 200,
        "result": {
            "postcode": "TR1 1AA",
            "country": "England",
            "lsoa": "Cornwall 044A",
            "codes": {"lsoa": "E01018807"},
        },
    },
    "TS11AP": None,
    "WA11BA": {
        "status": 200,
        "terminated": True,
        "result": {
            "postcode": "WA1 1BA",
            "country": "",
            "lsoa": "",
            "codes": {"lsoa": ""},
        },
    },
    "WR11DU": {
        "status": 200,
        "result": {
            "postcode": "WR1 1DU",
            "country": "England",
            "lsoa": "Worcester 007C",
            "codes": {"lsoa": "E01032282"},
        },
    },
    "TS183WH": {
        "status": 200,
        "result": {
            "postcode": "TS18 3WH",
            "country": "England",
            "lsoa": "Stockton-on-Tees 045A",
            "codes": {
                "lsoa": "E01012264",
                "lsoa11": "E01012264",
                "lsoa21": "E01035201",
            },
        },
    },
    # Invalid postcodes for error testing
    "INVALID": None,
    "XXXXXX": None,
    "ZZ99ZZ": None,
}


def get_mock_postcode_response(postcode: str) -> dict | None:
    """
    Get mock postcodes.io response for a given postcode.
    Returns None if postcode not found (simulates 404).
    """
    # Normalize postcode: remove spaces, uppercase
    normalized = postcode.replace(" ", "").upper()
    resp = MOCK_POSTCODE_RESPONSES.get(normalized)
    # If we have a mocked response dict, ensure it contains the
    # year-specific keys expected by production code: `lsoa11` and
    # `lsoa21`. Older captured responses only included `lsoa`, which
    # causes tests to fail when code looks up `codes['lsoa11']` or
    # `codes['lsoa21']`.
    if isinstance(resp, dict):
        result = resp.get("result")
        if isinstance(result, dict):
            codes = result.get("codes")
            if isinstance(codes, dict) and "lsoa" in codes:
                # Populate missing year-specific keys with the same value
                # so tests can simulate either 2011 or 2021 LSOA codes.
                if "lsoa11" not in codes:
                    codes["lsoa11"] = codes.get("lsoa", "")
                if "lsoa21" not in codes:
                    codes["lsoa21"] = codes.get("lsoa", "")
    return resp
