#!/bin/bash

# scripts may need to be made executable on some platforms before they can be run
# chmod +x <filename> is the command to do this on unixy systems

# starts all docker compose services
mkdir datadb
echo "✨ Running RCPCH Census Platform docker 🛠️"
docker compose -f docker-compose.dev-init.yml up