NORTHERN_IRELAND_IMD_DATA = [
    {
        "postcode": "BT1 1EX",
        "imd_rank": "29",
        "income_rank": "88",
        "employment_rank": "30",
        "health_rank": "11",
        "education_rank": "46",
        "access_services_rank": "788",
        "living_environment_rank": "258",
        "crime_rank": "9",
    },
    {
        "postcode": "BT1 4GA",
        "imd_rank": "163",
        "income_rank": "464",
        "employment_rank": "128",
        "health_rank": "70",
        "education_rank": "104",
        "access_services_rank": "739",
        "living_environment_rank": "187",
        "crime_rank": "127",
    },
    {
        "postcode": "BT11 9AE",
        "imd_rank": "297",
        "income_rank": "692",
        "employment_rank": "212",
        "health_rank": "244",
        "education_rank": "293",
        "access_services_rank": "873",
        "living_environment_rank": "33",
        "crime_rank": "25",
    },
    {
        "postcode": "BT23 5TP",
        "imd_rank": "701",
        "income_rank": "655",
        "employment_rank": "714",
        "health_rank": "608",
        "education_rank": "635",
        "access_services_rank": "299",
        "living_environment_rank": "444",
        "crime_rank": "637",
    },
    {
        "postcode": "BT12 5JE",
        "imd_rank": "146",
        "income_rank": "438",
        "employment_rank": "146",
        "health_rank": "68",
        "education_rank": "72",
        "access_services_rank": "769",
        "living_environment_rank": "275",
        "crime_rank": "39",
    },
    {
        "postcode": "BT35 9AN",
        "imd_rank": "57",
        "income_rank": "5",
        "employment_rank": "109",
        "health_rank": "229",
        "education_rank": "276",
        "access_services_rank": "208",
        "living_environment_rank": "81",
        "crime_rank": "783",
    },
    {
        "postcode": "BT81 7GY",
        "imd_rank": "166",
        "income_rank": "81",
        "employment_rank": "196",
        "health_rank": "310",
        "education_rank": "236",
        "access_services_rank": "180",
        "living_environment_rank": "668",
        "crime_rank": "571",
    },
    {
        "postcode": "BT80 8HD",
        "imd_rank": "296",
        "income_rank": "243",
        "employment_rank": "297",
        "health_rank": "189",
        "education_rank": "330",
        "access_services_rank": "552",
        "living_environment_rank": "809",
        "crime_rank": "204",
    },
    {
        "postcode": "BT74 7NR",
        "imd_rank": "409",
        "income_rank": "410",
        "employment_rank": "331",
        "health_rank": "374",
        "education_rank": "336",
        "access_services_rank": "365",
        "living_environment_rank": "811",
        "crime_rank": "249",
    },
]
