NI_2017_IMD_RANKS = [
    {
        "Postcode": "BT52 1PF",
        "SOA": "Central Coleraine",
        "Urban_Rural": "Urban",
        "Population_2017": "2,175",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 137,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT28 3WD",
        "SOA": "Ballymacoss 3",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "4,283",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 723,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT20 5DL",
        "SOA": "Harbour 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,554",
        "LGD": "Ards and North Down",
        "IMD_Rank": 174,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT7 3FH",
        "SOA": "Rosetta 1",
        "Urban_Rural": "Urban",
        "Population_2017": "3,221",
        "LGD": "Belfast",
        "IMD_Rank": 846,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT94 4QD",
        "SOA": "Maguires Bridge",
        "Urban_Rural": "Rural",
        "Population_2017": "3,262",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 394,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT36 4AD",
        "SOA": "Mallusk 2",
        "Urban_Rural": "Urban",
        "Population_2017": "5,976",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 792,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT51 4PX",
        "SOA": "Ringsend",
        "Urban_Rural": "Rural",
        "Population_2017": "2,472",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 341,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT61 9JT",
        "SOA": "Rich Hill 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,230",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 786,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 1BJ",
        "SOA": "Mullaghmore",
        "Urban_Rural": "Urban",
        "Population_2017": "2,578",
        "LGD": "Mid Ulster",
        "IMD_Rank": 355,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT7 3GX",
        "SOA": "Ballynafeigh 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,781",
        "LGD": "Belfast",
        "IMD_Rank": 579,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT80 8WX",
        "SOA": "Oldtown",
        "Urban_Rural": "Urban",
        "Population_2017": "2,453",
        "LGD": "Mid Ulster",
        "IMD_Rank": 296,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT60 4SS",
        "SOA": "Killylea",
        "Urban_Rural": "Rural",
        "Population_2017": "2,539",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 432,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 3NP",
        "SOA": "Castlecaulfield",
        "Urban_Rural": "Rural",
        "Population_2017": "2,893",
        "LGD": "Mid Ulster",
        "IMD_Rank": 625,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT38 9NN",
        "SOA": "Blackhead",
        "Urban_Rural": "Rural",
        "Population_2017": "2,033",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 605,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT38 8JN",
        "SOA": "Northland",
        "Urban_Rural": "Urban",
        "Population_2017": "1,450",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 65,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT62 2AP",
        "SOA": "Tandragee",
        "Urban_Rural": "Rural",
        "Population_2017": "2,983",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 353,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 2ND",
        "SOA": "Augher",
        "Urban_Rural": "Rural",
        "Population_2017": "2,377",
        "LGD": "Mid Ulster",
        "IMD_Rank": 479,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT2 8JL",
        "SOA": "Shaftesbury 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,415",
        "LGD": "Belfast",
        "IMD_Rank": 163,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT4 3LS",
        "SOA": "Stormont 3",
        "Urban_Rural": "Urban",
        "Population_2017": "2,095",
        "LGD": "Belfast",
        "IMD_Rank": 876,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 2HL",
        "SOA": "Ballygawley",
        "Urban_Rural": "Rural",
        "Population_2017": "2,692",
        "LGD": "Mid Ulster",
        "IMD_Rank": 232,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT19 6LS",
        "SOA": "Groomsport",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "3,040",
        "LGD": "Ards and North Down",
        "IMD_Rank": 768,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT48 7ET",
        "SOA": "Strand 1 Derry",
        "Urban_Rural": "Urban",
        "Population_2017": "1,878",
        "LGD": "Derry and Strabane",
        "IMD_Rank": 5,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT5 6QD",
        "SOA": "Lower Braniel",
        "Urban_Rural": "Urban",
        "Population_2017": "2,481",
        "LGD": "Belfast",
        "IMD_Rank": 641,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT80 8WX",
        "SOA": "Oldtown",
        "Urban_Rural": "Urban",
        "Population_2017": "2,453",
        "LGD": "Mid Ulster",
        "IMD_Rank": 296,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT78 5ED",
        "SOA": "Strule",
        "Urban_Rural": "Urban",
        "Population_2017": "1,485",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 168,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 7SJ",
        "SOA": "Moy",
        "Urban_Rural": "Rural",
        "Population_2017": "3,277",
        "LGD": "Mid Ulster",
        "IMD_Rank": 558,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT74 7JZ",
        "SOA": "Rossorry",
        "Urban_Rural": "Urban",
        "Population_2017": "2,465",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 409,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT25 1AQ",
        "SOA": "Dromore South 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,020",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 785,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 5BR",
        "SOA": "Killycolpy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,790",
        "LGD": "Mid Ulster",
        "IMD_Rank": 314,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT79 7RT",
        "SOA": "Owenkillew",
        "Urban_Rural": "Rural",
        "Population_2017": "2,467",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 257,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT8 7YQ",
        "SOA": "Beechill 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,709",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 733,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT49 0EP",
        "SOA": "Roeside",
        "Urban_Rural": "Urban",
        "Population_2017": "1,483",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 191,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT67 9AH",
        "SOA": "Woodville 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,554",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 14,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT23 5YH",
        "SOA": "Comber East 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,745",
        "LGD": "Ards and North Down",
        "IMD_Rank": 325,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT66 6EY",
        "SOA": "Court 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,498",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 54,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT35 6LW",
        "SOA": "Tullyhappy",
        "Urban_Rural": "Rural",
        "Population_2017": "3,476",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 322,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT48 7EE",
        "SOA": "Strand 1 Derry",
        "Urban_Rural": "Urban",
        "Population_2017": "1,878",
        "LGD": "Derry and Strabane",
        "IMD_Rank": 5,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 5BR",
        "SOA": "Killycolpy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,790",
        "LGD": "Mid Ulster",
        "IMD_Rank": 314,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT19 6DJ",
        "SOA": "Ballymaconnell 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,201",
        "LGD": "Ards and North Down",
        "IMD_Rank": 751,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT52 1DU",
        "SOA": "Central Coleraine",
        "Urban_Rural": "Urban",
        "Population_2017": "2,175",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 137,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT32 3YJ",
        "SOA": "Fort",
        "Urban_Rural": "Urban",
        "Population_2017": "2,285",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 503,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT20 5QW",
        "SOA": "Churchill 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,444",
        "LGD": "Ards and North Down",
        "IMD_Rank": 788,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT39 9NA",
        "SOA": "Ballynure 1",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "1,618",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 653,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT26 6QX",
        "SOA": "Hillsborough 2",
        "Urban_Rural": "Rural",
        "Population_2017": "2,167",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 812,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT6 0HG",
        "SOA": "Rosetta 3",
        "Urban_Rural": "Urban",
        "Population_2017": "1,570",
        "LGD": "Belfast",
        "IMD_Rank": 881,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT49 0JQ",
        "SOA": "Magilligan",
        "Urban_Rural": "Rural",
        "Population_2017": "2,503",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 491,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT42 2HB",
        "SOA": "Harryville",
        "Urban_Rural": "Urban",
        "Population_2017": "2,119",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 228,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT13 1FT",
        "SOA": "Crumlin 1 Belfast",
        "Urban_Rural": "Urban",
        "Population_2017": "1,997",
        "LGD": "Belfast",
        "IMD_Rank": 24,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT40 2RX",
        "SOA": "Carncastle",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,840",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 729,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT18 0BD",
        "SOA": "Cultra",
        "Urban_Rural": "Urban",
        "Population_2017": "2,500",
        "LGD": "Ards and North Down",
        "IMD_Rank": 762,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 2TL",
        "SOA": "Pomeroy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,359",
        "LGD": "Mid Ulster",
        "IMD_Rank": 167,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT28 1XJ",
        "SOA": "Hilden 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,639",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 190,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT92 7NJ",
        "SOA": "Rosslea",
        "Urban_Rural": "Rural",
        "Population_2017": "2,153",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 114,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT45 8AA",
        "SOA": "Castledawson 2",
        "Urban_Rural": "Rural",
        "Population_2017": "1,782",
        "LGD": "Mid Ulster",
        "IMD_Rank": 607,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT39 0QL",
        "SOA": "Doagh 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,818",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 799,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT28 1JA",
        "SOA": "Knockmore 1",
        "Urban_Rural": "Urban",
        "Population_2017": "3,159",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 576,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT51 4DR",
        "SOA": "Ringsend",
        "Urban_Rural": "Rural",
        "Population_2017": "2,472",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 341,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT22 2HE",
        "SOA": "Carrowdore 2",
        "Urban_Rural": "Rural",
        "Population_2017": "1,963",
        "LGD": "Ards and North Down",
        "IMD_Rank": 548,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT78 2RN",
        "SOA": "Newtownsaville",
        "Urban_Rural": "Rural",
        "Population_2017": "2,495",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 452,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT34 4HL",
        "SOA": "Lisnacree",
        "Urban_Rural": "Rural",
        "Population_2017": "3,213",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 336,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT27 4AB",
        "SOA": "Hilden 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,639",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 190,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT61 9PH",
        "SOA": "Rich Hill 2",
        "Urban_Rural": "Rural",
        "Population_2017": "1,709",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 637,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT34 3LF",
        "SOA": "Clonallan 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,048",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 133,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT47 3XS",
        "SOA": "Altnagelvin 3",
        "Urban_Rural": "Urban",
        "Population_2017": "1,625",
        "LGD": "Derry and Strabane",
        "IMD_Rank": 525,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT39 9TB",
        "SOA": "Doagh 2",
        "Urban_Rural": "Rural",
        "Population_2017": "1,877",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 694,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT60 2LU",
        "SOA": "Milford",
        "Urban_Rural": "Rural",
        "Population_2017": "3,039",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 600,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 1LB",
        "SOA": "Caledon",
        "Urban_Rural": "Rural",
        "Population_2017": "2,696",
        "LGD": "Mid Ulster",
        "IMD_Rank": 465,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT45 6LN",
        "SOA": "Ballymaguigan",
        "Urban_Rural": "Rural",
        "Population_2017": "2,988",
        "LGD": "Mid Ulster",
        "IMD_Rank": 664,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT45 7XQ",
        "SOA": "The Loop",
        "Urban_Rural": "Rural",
        "Population_2017": "3,121",
        "LGD": "Mid Ulster",
        "IMD_Rank": 531,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT55 7AE",
        "SOA": "Portstewart",
        "Urban_Rural": "Urban",
        "Population_2017": "1,702",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 253,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT23 6JH",
        "SOA": "Ballygowan 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,751",
        "LGD": "Ards and North Down",
        "IMD_Rank": 744,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT44 0PU",
        "SOA": "Glenaan & Glendun",
        "Urban_Rural": "Rural",
        "Population_2017": "2,383",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 499,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT8 7QN",
        "SOA": "Beechill 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,709",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 733,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT42 1NB",
        "SOA": "Ahoghill 2",
        "Urban_Rural": "Rural",
        "Population_2017": "2,617",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 778,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT25 1LQ",
        "SOA": "Quilly",
        "Urban_Rural": "Rural",
        "Population_2017": "2,535",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 639,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 5AS",
        "SOA": "Killycolpy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,790",
        "LGD": "Mid Ulster",
        "IMD_Rank": 314,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT19 1DT",
        "SOA": "Springhill 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,410",
        "LGD": "Ards and North Down",
        "IMD_Rank": 731,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT4 3QL",
        "SOA": "Stormont 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,599",
        "LGD": "Belfast",
        "IMD_Rank": 889,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT34 5UP",
        "SOA": "Spelga",
        "Urban_Rural": "Rural",
        "Population_2017": "3,723",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 284,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT49 9EY",
        "SOA": "Forest",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,470",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 446,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT45 7JN",
        "SOA": "Draperstown",
        "Urban_Rural": "Rural",
        "Population_2017": "3,152",
        "LGD": "Mid Ulster",
        "IMD_Rank": 389,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT51 5AA",
        "SOA": "Garvagh",
        "Urban_Rural": "Rural",
        "Population_2017": "2,914",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 272,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT24 7LX",
        "SOA": "Kilmore 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,678",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 735,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT70 2RD",
        "SOA": "Pomeroy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,359",
        "LGD": "Mid Ulster",
        "IMD_Rank": 167,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT47 4HR",
        "SOA": "Claudy 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,566",
        "LGD": "Derry and Strabane",
        "IMD_Rank": 490,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT32 3LA",
        "SOA": "The Cut",
        "Urban_Rural": "Urban",
        "Population_2017": "1,676",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 120,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT67 0LH",
        "SOA": "Moira 1",
        "Urban_Rural": "Rural",
        "Population_2017": "3,057",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 804,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT62 3PZ",
        "SOA": "Brownstown 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,806",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 447,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT40 1TB",
        "SOA": "Gardenmore",
        "Urban_Rural": "Urban",
        "Population_2017": "1,880",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 595,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT40 3HQ",
        "SOA": "Glynn",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,009",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 555,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT15 3BU",
        "SOA": "Chichester Park 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,036",
        "LGD": "Belfast",
        "IMD_Rank": 122,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT60 2DJ",
        "SOA": "Poyntz Pass",
        "Urban_Rural": "Rural",
        "Population_2017": "2,893",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 294,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 5DQ",
        "SOA": "Washing Bay",
        "Urban_Rural": "Rural",
        "Population_2017": "3,271",
        "LGD": "Mid Ulster",
        "IMD_Rank": 476,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT7 1NA",
        "SOA": "Botanic 4",
        "Urban_Rural": "Urban",
        "Population_2017": "1,870",
        "LGD": "Belfast",
        "IMD_Rank": 189,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT6 0JJ",
        "SOA": "Wynchurch",
        "Urban_Rural": "Urban",
        "Population_2017": "2,278",
        "LGD": "Belfast",
        "IMD_Rank": 836,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 6DH",
        "SOA": "Killymeal",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "3,089",
        "LGD": "Mid Ulster",
        "IMD_Rank": 624,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT19 1ZT",
        "SOA": "Crawfordsburn",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,891",
        "LGD": "Ards and North Down",
        "IMD_Rank": 824,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT32 4AS",
        "SOA": "The Cut",
        "Urban_Rural": "Urban",
        "Population_2017": "1,676",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 120,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT23 4YJ",
        "SOA": "Ballyrainey",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,451",
        "LGD": "Ards and North Down",
        "IMD_Rank": 240,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT46 5JQ",
        "SOA": "Swatragh 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,887",
        "LGD": "Mid Ulster",
        "IMD_Rank": 562,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT41 3HW",
        "SOA": "Cranfield",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,755",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 613,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT74 6AA",
        "SOA": "Devenish",
        "Urban_Rural": "Urban",
        "Population_2017": "1,639",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 44,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT8 7HY",
        "SOA": "Newtownbreda",
        "Urban_Rural": "Urban",
        "Population_2017": "2,679",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 815,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT7 1JR",
        "SOA": "Botanic 4",
        "Urban_Rural": "Urban",
        "Population_2017": "1,870",
        "LGD": "Belfast",
        "IMD_Rank": 189,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT51 5PF",
        "SOA": "Garvagh",
        "Urban_Rural": "Rural",
        "Population_2017": "2,914",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 272,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT6 9JS",
        "SOA": "Downshire",
        "Urban_Rural": "Urban",
        "Population_2017": "2,484",
        "LGD": "Belfast",
        "IMD_Rank": 687,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT35 6SD",
        "SOA": "Tullyhappy",
        "Urban_Rural": "Rural",
        "Population_2017": "3,476",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 322,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT7 2HP",
        "SOA": "Shaftesbury 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,415",
        "LGD": "Belfast",
        "IMD_Rank": 163,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT23 7QB",
        "SOA": "Conlig 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,785",
        "LGD": "Ards and North Down",
        "IMD_Rank": 497,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT43 5NW",
        "SOA": "Craigywarren",
        "Urban_Rural": "Rural",
        "Population_2017": "2,639",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 590,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT37 0ST",
        "SOA": "Rostulla 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,323",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 628,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT30 9AJ",
        "SOA": "Drumaness 2",
        "Urban_Rural": "Rural",
        "Population_2017": "2,272",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 629,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT9 5BN",
        "SOA": "Botanic 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,513",
        "LGD": "Belfast",
        "IMD_Rank": 580,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT38 7LE",
        "SOA": "Boneybefore",
        "Urban_Rural": "Urban",
        "Population_2017": "1,616",
        "LGD": "Mid and East Antrim",
        "IMD_Rank": 791,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT80 9HG",
        "SOA": "Oaklands",
        "Urban_Rural": "Rural",
        "Population_2017": "2,296",
        "LGD": "Mid Ulster",
        "IMD_Rank": 397,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT61 8DL",
        "SOA": "Ballymartrim",
        "Urban_Rural": "Rural",
        "Population_2017": "2,916",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 498,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT41 1NJ",
        "SOA": "Ballycraigy",
        "Urban_Rural": "Urban",
        "Population_2017": "1,888",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 259,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT33 0RW",
        "SOA": "Donard 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,589",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 671,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT30 9QG",
        "SOA": "Killyleagh",
        "Urban_Rural": "Rural",
        "Population_2017": "3,104",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 381,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT71 5HG",
        "SOA": "Killycolpy",
        "Urban_Rural": "Rural",
        "Population_2017": "2,790",
        "LGD": "Mid Ulster",
        "IMD_Rank": 314,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT5 4QA",
        "SOA": "The Mount 1",
        "Urban_Rural": "Urban",
        "Population_2017": "3,115",
        "LGD": "Belfast",
        "IMD_Rank": 80,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT67 0UQ",
        "SOA": "Maghaberry 1",
        "Urban_Rural": "Rural",
        "Population_2017": "2,743",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 712,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT74 7NF",
        "SOA": "Portora",
        "Urban_Rural": "Urban",
        "Population_2017": "3,166",
        "LGD": "Fermanagh and Omagh",
        "IMD_Rank": 214,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT28 3PP",
        "SOA": "Wallace Park 2",
        "Urban_Rural": "Urban",
        "Population_2017": "2,240",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 842,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT2 7DX",
        "SOA": "Shaftesbury 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,415",
        "LGD": "Belfast",
        "IMD_Rank": 163,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT41 1QZ",
        "SOA": "Springfarm 1",
        "Urban_Rural": "Urban",
        "Population_2017": "3,015",
        "LGD": "Antrim and Newtownabbey",
        "IMD_Rank": 623,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT28 2NT",
        "SOA": "Ballinderry 1",
        "Urban_Rural": "Rural",
        "Population_2017": "2,335",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 673,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT35 6BP",
        "SOA": "Drumgullion 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,400",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 70,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT20 3QW",
        "SOA": "Princetown",
        "Urban_Rural": "Urban",
        "Population_2017": "2,889",
        "LGD": "Ards and North Down",
        "IMD_Rank": 818,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT66 6HZ",
        "SOA": "Woodville 2",
        "Urban_Rural": "Urban",
        "Population_2017": "2,192",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 772,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT47 4DU",
        "SOA": "Claudy 1",
        "Urban_Rural": "Rural",
        "Population_2017": "1,566",
        "LGD": "Derry and Strabane",
        "IMD_Rank": 490,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT62 3LR",
        "SOA": "Brownstown 1",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "1,743",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 423,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT34 4GG",
        "SOA": "Kilkeel Central 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,883",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 540,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT62 4DX",
        "SOA": "Ballybay",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,928",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 200,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT12 5JJ",
        "SOA": "Shaftesbury 2",
        "Urban_Rural": "Urban",
        "Population_2017": "2,828",
        "LGD": "Belfast",
        "IMD_Rank": 146,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT30 9DL",
        "SOA": "Derryboy 2",
        "Urban_Rural": "Rural",
        "Population_2017": "1,407",
        "LGD": "Newry, Mourne and Down",
        "IMD_Rank": 464,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT1 4GA",
        "SOA": "Shaftesbury 1",
        "Urban_Rural": "Urban",
        "Population_2017": "2,415",
        "LGD": "Belfast",
        "IMD_Rank": 163,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT45 5EW",
        "SOA": "Knockcloghrim",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "2,886",
        "LGD": "Mid Ulster",
        "IMD_Rank": 674,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT56 8HW",
        "SOA": "Hopefield 2",
        "Urban_Rural": "Urban",
        "Population_2017": "1,967",
        "LGD": "Causeway Coast and Glens",
        "IMD_Rank": 593,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT62 3RJ",
        "SOA": "Annagh 1",
        "Urban_Rural": "Mixed urban/rural",
        "Population_2017": "1,722",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 583,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT32 5PS",
        "SOA": "Katesbridge",
        "Urban_Rural": "Rural",
        "Population_2017": "2,829",
        "LGD": "Armagh, Banbridge and Craigavon",
        "IMD_Rank": 449,
        "Total_SOAs": 890,
    },
    {
        "Postcode": "BT27 4XD",
        "SOA": "Hilden 1",
        "Urban_Rural": "Urban",
        "Population_2017": "1,639",
        "LGD": "Lisburn and Castlereagh",
        "IMD_Rank": 190,
        "Total_SOAs": 890,
    },
]
