#!/usr/bin/env python3
"""
Script to capture real postcodes.io API responses for all test postcodes.
Run this script to generate mock data that matches what postcodes.io returns.

Usage:
    python scripts/capture_postcode_responses.py > tests/postcode_mock_data.py
"""

import json
import re
import sys
import time
from pathlib import Path

import requests


# Collect all unique postcodes from test files
def extract_postcodes_from_file(filepath: Path) -> set[str]:
    """Extract all postcode-like strings from a Python file."""
    postcodes = set()
    content = filepath.read_text()

    # Pattern to match UK postcodes in quotes
    # Matches: "AL1 3AG", "CF10 3NQ", "BT48 7ET", etc.
    pattern = r'"([A-Z]{1,2}[0-9R][0-9A-Z]?\s*[0-9][A-Z]{2})"'

    matches = re.findall(pattern, content)
    for match in matches:
        # Normalize: remove spaces, uppercase
        normalized = match.replace(" ", "").upper()
        postcodes.add(normalized)

    return postcodes


def get_postcode_info(postcode: str) -> dict | None:
    """Fetch postcode info from postcodes.io API."""
    # Add space back for API call
    clean_postcode = postcode.replace(" ", "")

    try:
        response = requests.get(
            f"https://api.postcodes.io/postcodes/{clean_postcode}", timeout=10
        )
        if response.status_code == 200:
            data = response.json()
            data["terminated"] = False
            return data
        elif response.status_code == 404:
            # Try terminated postcodes endpoint
            response = requests.get(
                f"https://api.postcodes.io/terminated_postcodes/{clean_postcode}",
                timeout=10,
            )
            if response.status_code == 200:
                data = response.json()
                # Mark as terminated - these don't have lsoa codes
                data["terminated"] = True
                return data
        return None
    except Exception as e:
        print(f"Error fetching {postcode}: {e}", file=sys.stderr)
        return None


def main():
    # Get the project root
    project_root = Path(__file__).parent.parent
    tests_dir = project_root / "tests"

    # Collect all postcodes from test files
    all_postcodes = set()
    for test_file in tests_dir.glob("*_tests.py"):
        postcodes = extract_postcodes_from_file(test_file)
        all_postcodes.update(postcodes)
        print(f"Found {len(postcodes)} postcodes in {test_file.name}", file=sys.stderr)

    print(f"\nTotal unique postcodes: {len(all_postcodes)}", file=sys.stderr)

    # Fetch data for each postcode
    postcode_data = {}
    for i, postcode in enumerate(sorted(all_postcodes), 1):
        print(f"Fetching {i}/{len(all_postcodes)}: {postcode}...", file=sys.stderr)
        data = get_postcode_info(postcode)
        if data:
            postcode_data[postcode] = data
        else:
            print(f"  WARNING: No data for {postcode}", file=sys.stderr)
            postcode_data[postcode] = None

        # Rate limiting - be nice to the API
        time.sleep(0.1)

    # Generate Python file
    print('"""', file=sys.stdout)
    print("Mock postcodes.io API responses for testing.", file=sys.stdout)
    print(
        "This file was auto-generated by scripts/capture_postcode_responses.py",
        file=sys.stdout,
    )
    print("", file=sys.stdout)
    print("To regenerate:", file=sys.stdout)
    print(
        "    python scripts/capture_postcode_responses.py > tests/postcode_mock_data.py",
        file=sys.stdout,
    )
    print('"""', file=sys.stdout)
    print("", file=sys.stdout)
    print("# Mock postcodes.io API responses for test postcodes", file=sys.stdout)
    print("# Format: {postcode (no spaces, uppercase): response_data}", file=sys.stdout)
    print("MOCK_POSTCODE_RESPONSES = {", file=sys.stdout)

    for postcode in sorted(postcode_data.keys()):
        data = postcode_data[postcode]
        if data is None:
            print(f'    "{postcode}": None,', file=sys.stdout)
        else:
            # Extract just what we need
            result = data.get("result", {})
            if result:
                country = result.get("country", "")
                lsoa = result.get("lsoa", "")
                lsoa_code = result.get("codes", {}).get("lsoa", "")
                formatted_postcode = result.get("postcode", postcode)
                terminated = data.get("terminated", False)

                print(f'    "{postcode}": {{', file=sys.stdout)
                print(f'        "status": 200,', file=sys.stdout)
                if terminated:
                    print(f'        "terminated": True,', file=sys.stdout)
                print(f'        "result": {{', file=sys.stdout)
                print(
                    f'            "postcode": "{formatted_postcode}",', file=sys.stdout
                )
                print(f'            "country": "{country}",', file=sys.stdout)
                print(f'            "lsoa": "{lsoa}",', file=sys.stdout)
                print(
                    f'            "codes": {{"lsoa": "{lsoa_code}"}},', file=sys.stdout
                )
                print(f"        }},", file=sys.stdout)
                print(f"    }},", file=sys.stdout)
            else:
                print(f'    "{postcode}": None,', file=sys.stdout)

    # Add invalid postcodes
    print("    # Invalid postcodes for error testing", file=sys.stdout)
    print('    "INVALID": None,', file=sys.stdout)
    print('    "XXXXXX": None,', file=sys.stdout)
    print('    "ZZ99ZZ": None,', file=sys.stdout)
    print("}", file=sys.stdout)
    print("", file=sys.stdout)
    print("", file=sys.stdout)
    print(
        "def get_mock_postcode_response(postcode: str) -> dict | None:", file=sys.stdout
    )
    print('    """', file=sys.stdout)
    print("    Get mock postcodes.io response for a given postcode.", file=sys.stdout)
    print("    Returns None if postcode not found (simulates 404).", file=sys.stdout)
    print('    """', file=sys.stdout)
    print("    # Normalize postcode: remove spaces, uppercase", file=sys.stdout)
    print('    normalized = postcode.replace(" ", "").upper()', file=sys.stdout)
    print("    return MOCK_POSTCODE_RESPONSES.get(normalized)", file=sys.stdout)

    print(
        f"\nDone! Generated mock data for {len(postcode_data)} postcodes.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
