# Generated by Django 4.1.3 on 2022-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_zone_name",
                    models.CharField(max_length=50, verbose_name="Data Zone Name"),
                ),
                ("year", models.IntegerField(verbose_name="MSOA Year")),
            ],
        ),
        migrations.CreateModel(
            name="LocalAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_authority_district_code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Local Authority District code (2019)",
                    ),
                ),
                (
                    "local_authority_district_name",
                    models.CharField(
                        max_length=50,
                        verbose_name="Local Authority District name (2019)",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(verbose_name="Local Authority District Year"),
                ),
            ],
            options={
                "verbose_name": ("Local Authority",),
                "verbose_name_plural": "Local Authorities",
            },
        ),
        migrations.CreateModel(
            name="MSOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msoa_code",
                    models.CharField(
                        help_text="Middle Layer Super Output Layer code",
                        max_length=50,
                        unique=True,
                        verbose_name="MSOA Code",
                    ),
                ),
                (
                    "msoa_name",
                    models.CharField(
                        help_text="Middle Layer Super Output Layer name",
                        max_length=50,
                        verbose_name="MSOA name",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        verbose_name="Middle Layer Super Output Layer Year"
                    ),
                ),
                (
                    "local_authority_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.localauthority",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ward_code",
                    models.CharField(
                        help_text="Ward code",
                        max_length=50,
                        unique=True,
                        verbose_name="Ward Code",
                    ),
                ),
                (
                    "ward_name",
                    models.CharField(
                        help_text="Ward name", max_length=50, verbose_name="Ward name"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Ward year")),
                (
                    "msoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.msoa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LSOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lsoa_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="LSOA code (2011)"
                    ),
                ),
                (
                    "lsoa_name",
                    models.CharField(max_length=50, verbose_name="LSOA name (2011)"),
                ),
                ("year", models.IntegerField(verbose_name="Year LSOA calculated")),
                (
                    "total_population_mid_2015",
                    models.IntegerField(
                        help_text="Total population: mid 2015 (excluding prisoners)",
                        null=True,
                        verbose_name="Total population: mid 2015 (excluding prisoners)",
                    ),
                ),
                (
                    "dependent_children_mid_2015",
                    models.IntegerField(
                        help_text="Dependent Children aged 0-15: mid 2015 (excluding prisoners)",
                        null=True,
                        verbose_name="Dependent Children aged 0-15: mid 2015 (excluding prisoners)",
                    ),
                ),
                (
                    "population_16_59_mid_2015",
                    models.IntegerField(
                        help_text="Population aged 16-59: mid 2015 (excluding prisoners)",
                        null=True,
                        verbose_name="Population aged 16-59: mid 2015 (excluding prisoners)",
                    ),
                ),
                (
                    "older_population_over_16_mid_2015",
                    models.IntegerField(
                        help_text="Older population aged 60 and over: mid 2015 (excluding prisoners)",
                        null=True,
                        verbose_name="Older population aged 60 and over: mid 2015 (excluding prisoners)",
                    ),
                ),
                (
                    "working_age_population_over_18_mid_2015",
                    models.IntegerField(
                        help_text="Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)",
                        null=True,
                        verbose_name="Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)",
                    ),
                ),
                (
                    "local_authority_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.localauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": ("LSOA",),
                "verbose_name_plural": "LSOAs",
            },
        ),
        migrations.CreateModel(
            name="IndexMultipleDeprivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imd_score",
                    models.IntegerField(
                        help_text="Index of Multiple Deprivation (IMD) Score",
                        null=True,
                        verbose_name="Index of Multiple Deprivation (IMD) Score",
                    ),
                ),
                (
                    "imd_rank",
                    models.IntegerField(
                        help_text="Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)",
                        verbose_name="Index of Multiple Deprivation",
                    ),
                ),
                (
                    "imd_decile",
                    models.IntegerField(
                        help_text="Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Index of Multiple Deprivation (IMD) Decile",
                    ),
                ),
                (
                    "income_score",
                    models.IntegerField(
                        help_text="Income Score (rate)",
                        null=True,
                        verbose_name="Income Score (rate)",
                    ),
                ),
                (
                    "income_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Income Score exponentially tranformed",
                        null=True,
                        verbose_name="Income Score exponentially tranformed",
                    ),
                ),
                (
                    "income_rank",
                    models.IntegerField(
                        help_text="Income Rank (where 1 is most deprived)",
                        verbose_name="Income Rank",
                    ),
                ),
                (
                    "income_decile",
                    models.IntegerField(
                        help_text="Income Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Income Decile",
                    ),
                ),
                (
                    "employment_score",
                    models.IntegerField(
                        help_text="Employment Score (rate)",
                        null=True,
                        verbose_name="Employment Score (rate)",
                    ),
                ),
                (
                    "employment_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Employment Score exponentially transformed",
                        null=True,
                        verbose_name="Employment Score exponentially transformed",
                    ),
                ),
                (
                    "employment_rank",
                    models.IntegerField(
                        help_text="Employment Rank (where 1 is most deprived)",
                        verbose_name="Employment Rank",
                    ),
                ),
                (
                    "employment_decile",
                    models.IntegerField(
                        help_text="Employment Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Employment Decile",
                    ),
                ),
                (
                    "education_skills_training_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Education, Skills and Training Score exponentially transformed",
                        null=True,
                        verbose_name="Education, Skills and Training Score exponentially transformed",
                    ),
                ),
                (
                    "education_skills_training_score",
                    models.IntegerField(
                        help_text="Education, Skills and Training Score (rate)",
                        null=True,
                        verbose_name="Education, Skills and Training Score (rate)",
                    ),
                ),
                (
                    "education_skills_training_rank",
                    models.IntegerField(
                        help_text="Education, Skills and Training Rank (where 1 is most deprived)",
                        verbose_name="Education, Skills and Training Rank",
                    ),
                ),
                (
                    "education_skills_training_decile",
                    models.IntegerField(
                        help_text="Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Education, Skills and Training Decile",
                    ),
                ),
                (
                    "children_young_people_sub_domain_score",
                    models.IntegerField(
                        help_text="Children and Young People Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Children and Young People Sub-domain Score (rate)",
                    ),
                ),
                (
                    "children_young_people_sub_domain_rank",
                    models.IntegerField(
                        help_text="Children and Young People Sub-domain Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Children and Young People Sub-domain Rank (where 1 is most deprived)",
                    ),
                ),
                (
                    "children_young_people_sub_domain_decile",
                    models.IntegerField(
                        help_text="Children and Young People Sub-domain Decile (where 1 is most deprived) Decile",
                        null=True,
                        verbose_name="Children and Young People Sub-domain Decile (where 1 is most deprived) Decile",
                    ),
                ),
                (
                    "adult_skills_sub_domain_score",
                    models.IntegerField(
                        help_text="Adult Skills Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Adult Skills Sub-domain Score (rate)",
                    ),
                ),
                (
                    "adult_skills_sub_domain_rank",
                    models.IntegerField(
                        help_text="Adult Skills Sub-domain Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Adult Skills Sub-domain Rank (where 1 is most deprived)",
                    ),
                ),
                (
                    "adult_skills_sub_domain_decile",
                    models.IntegerField(
                        help_text="Adult Skills Sub-domain Decile (where 1 is most deprived) Decile",
                        null=True,
                        verbose_name="Adult Skills Sub-domain Decile (where 1 is most deprived) Decile",
                    ),
                ),
                (
                    "health_deprivation_disability_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Health Deprivation and Disability Score exponentially transformed",
                        null=True,
                        verbose_name="Health Deprivation and Disability Score exponentially transformed",
                    ),
                ),
                (
                    "health_deprivation_disability_score",
                    models.IntegerField(
                        help_text="Health Deprivation and Disability Score (rate)",
                        null=True,
                        verbose_name="Health Deprivation and Disability Score (rate)",
                    ),
                ),
                (
                    "health_deprivation_disability_rank",
                    models.IntegerField(
                        help_text="Health Deprivation and Disability Rank (where 1 is most deprived)",
                        verbose_name="Health Deprivation and Disability Rank",
                    ),
                ),
                (
                    "health_deprivation_disability_decile",
                    models.IntegerField(
                        help_text="Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Health Deprivation and Disability Decile",
                    ),
                ),
                (
                    "crime_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Crime Score exponentially transformed",
                        null=True,
                        verbose_name="Crime Score exponentially transformed",
                    ),
                ),
                (
                    "crime_score",
                    models.IntegerField(
                        help_text="Crime Score (rate)",
                        null=True,
                        verbose_name="Crime Score (rate)",
                    ),
                ),
                (
                    "crime_rank",
                    models.IntegerField(
                        help_text="Crime Rank (where 1 is most deprived)",
                        verbose_name="Crime Rank",
                    ),
                ),
                (
                    "crime_decile",
                    models.IntegerField(
                        help_text="Crime Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Crime Decile",
                    ),
                ),
                (
                    "barriers_to_housing_services_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Barriers to Housing and Services Score Exponentially transformed",
                        null=True,
                        verbose_name="Barriers to Housing and Services Score Exponentially transformed",
                    ),
                ),
                (
                    "barriers_to_housing_services_score",
                    models.IntegerField(
                        help_text="Barriers to Housing and Services Score (rate)",
                        null=True,
                        verbose_name="Barriers to Housing and Services Score (rate)",
                    ),
                ),
                (
                    "barriers_to_housing_services_rank",
                    models.IntegerField(
                        help_text="Barriers to Housing and Services Rank (where 1 is most deprived)",
                        verbose_name="Barriers to Housing and Services Rank",
                    ),
                ),
                (
                    "barriers_to_housing_services_decile",
                    models.IntegerField(
                        help_text="Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Barriers to Housing and Services Decile",
                    ),
                ),
                (
                    "geographical_barriers_sub_domain_score",
                    models.IntegerField(
                        help_text="Geographical Barriers Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Geographical Barriers Sub-domain Score",
                    ),
                ),
                (
                    "geographical_barriers_sub_domain_rank",
                    models.IntegerField(
                        help_text="Geographical Barriers Sub-domain Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Geographical Barriers Sub-domain Rank",
                    ),
                ),
                (
                    "geographical_barriers_sub_domain_decile",
                    models.IntegerField(
                        help_text="Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Geographical Barriers Sub-domain Decile",
                    ),
                ),
                (
                    "wider_barriers_sub_domain_score",
                    models.IntegerField(
                        help_text="Wider Barriers Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Wider Barriers Sub-domain Score (rate)",
                    ),
                ),
                (
                    "wider_barriers_sub_domain_rank",
                    models.IntegerField(
                        help_text="Wider Barriers Sub-domain Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Wider Barriers Sub-domain Rank",
                    ),
                ),
                (
                    "wider_barriers_sub_domain_decile",
                    models.IntegerField(
                        help_text="Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Wider Barriers Sub-domain Decile",
                    ),
                ),
                (
                    "living_environment_score",
                    models.IntegerField(
                        help_text="Living Environment Score (rate)",
                        null=True,
                        verbose_name="Living Environment Score (rate)",
                    ),
                ),
                (
                    "living_environment_score_exponentially_transformed",
                    models.IntegerField(
                        help_text="Living Environment Score exponentially transformed",
                        null=True,
                        verbose_name="Living Environment Score exponentially transformed",
                    ),
                ),
                (
                    "living_environment_rank",
                    models.IntegerField(
                        help_text="Living Environment Rank (where 1 is most deprived)",
                        verbose_name="Living Environment Rank",
                    ),
                ),
                (
                    "living_environment_decile",
                    models.IntegerField(
                        help_text="Living Environment Decile (where 1 is most deprived 10% of LSOAs)",
                        verbose_name="Living Environment Decile",
                    ),
                ),
                (
                    "indoors_sub_domain_score",
                    models.IntegerField(
                        help_text="Indoors Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Indoors Sub-domain Score (rate)",
                    ),
                ),
                (
                    "indoors_sub_domain_rank",
                    models.IntegerField(
                        help_text="Indoors Sub-domain Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Indoors Sub-domain Rank",
                    ),
                ),
                (
                    "indoors_sub_domain_decile",
                    models.IntegerField(
                        help_text="Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Indoors Sub-domain Decile",
                    ),
                ),
                (
                    "outdoors_sub_domain_score",
                    models.IntegerField(
                        help_text="Outdoors Sub-domain Score (rate)",
                        null=True,
                        verbose_name="Outdoors Sub-domain Score (rate)",
                    ),
                ),
                (
                    "outdoors_sub_domain_rank",
                    models.IntegerField(
                        help_text="Outdoors Sub-domain Rank(where 1 is most deprived)",
                        null=True,
                        verbose_name="Outdoors Sub-domain Rank",
                    ),
                ),
                (
                    "outdoors_sub_domain_decile",
                    models.IntegerField(
                        help_text="Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Outdoors Sub-domain Decile",
                    ),
                ),
                (
                    "idaci_score",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Children Index (IDACI) Score (rate)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Children Index Score (rate)",
                    ),
                ),
                (
                    "idaci_rank",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Children Index Rank",
                    ),
                ),
                (
                    "idaci_decile",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Children Index Decile",
                    ),
                ),
                (
                    "idaopi_score",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Older People Index (IDAOPI) Score (rate)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Older People Index Score (rate)",
                    ),
                ),
                (
                    "idaopi_rank",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Older People Index (IDAOPI) Rank (where 1 is most deprived)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Older People Index Rank",
                    ),
                ),
                (
                    "idaopi_decile",
                    models.IntegerField(
                        help_text="Income Deprivation Affecting Older People Index (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)",
                        null=True,
                        verbose_name="Income Deprivation Affecting Older People Index Decile",
                    ),
                ),
                (
                    "lsoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.lsoa",
                    ),
                ),
            ],
        ),
    ]
