# Generated by Django 4.1.7 on 2023-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deprivation_scores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datazone",
            name="data_zone_name",
            field=models.CharField(max_length=100, verbose_name="Data Zone Name"),
        ),
    ]
