# Generated by Django 4.1.7 on 2023-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deprivation_scores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="adult_skills_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Adult Skills Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Adult Skills Sub-domain Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="barriers_to_housing_services_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Barriers to Housing and Services Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Barriers to Housing and Services Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="barriers_to_housing_services_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Barriers to Housing and Services Score Exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Barriers to Housing and Services Score Exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="children_young_people_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Children and Young People Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Children and Young People Sub-domain Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="crime_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Crime Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Crime Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="crime_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Crime Score exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Crime Score exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="education_skills_training_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Education, Skills and Training Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Education, Skills and Training Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="education_skills_training_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Education, Skills and Training Score exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Education, Skills and Training Score exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="employment_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Employment Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Employment Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="employment_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Employment Score exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Employment Score exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="geographical_barriers_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Geographical Barriers Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Geographical Barriers Sub-domain Score",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="health_deprivation_disability_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Health Deprivation and Disability Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Health Deprivation and Disability Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="health_deprivation_disability_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Health Deprivation and Disability Score exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Health Deprivation and Disability Score exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="idaci_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Income Deprivation Affecting Children Index (IDACI) Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Income Deprivation Affecting Children Index Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="idaopi_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Income Deprivation Affecting Older People Index (IDAOPI) Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Income Deprivation Affecting Older People Index Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="imd_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Index of Multiple Deprivation (IMD) Score",
                max_digits=5,
                null=True,
                verbose_name="Index of Multiple Deprivation (IMD) Score",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="income_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Income Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Income Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="income_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Income Score exponentially tranformed",
                max_digits=5,
                null=True,
                verbose_name="Income Score exponentially tranformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="indoors_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Indoors Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Indoors Sub-domain Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="living_environment_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Living Environment Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Living Environment Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="living_environment_score_exponentially_transformed",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Living Environment Score exponentially transformed",
                max_digits=5,
                null=True,
                verbose_name="Living Environment Score exponentially transformed",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="outdoors_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Outdoors Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Outdoors Sub-domain Score (rate)",
            ),
        ),
        migrations.AlterField(
            model_name="indexmultipledeprivation",
            name="wider_barriers_sub_domain_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Wider Barriers Sub-domain Score (rate)",
                max_digits=5,
                null=True,
                verbose_name="Wider Barriers Sub-domain Score (rate)",
            ),
        ),
    ]
