# Generated by Django 5.2 on 2025-04-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0002_alter_datazone_data_zone_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationDensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("perc_buff200", models.FloatField(blank=True, null=True)),
                ("perc_buff300", models.FloatField(blank=True, null=True)),
                ("perc_buff1k", models.FloatField(blank=True, null=True)),
                ("perc_buff2k", models.FloatField(blank=True, null=True)),
                ("perc_buff5k", models.FloatField(blank=True, null=True)),
                ("perc_buff10k", models.FloatField(blank=True, null=True)),
                ("imd_decile", models.IntegerField(blank=True, null=True)),
                ("population_density_2011", models.FloatField(blank=True, null=True)),
                ("population_2011", models.IntegerField(blank=True, null=True)),
                ("buff200_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff300_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff1k_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff2k_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff5k_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff10k_popdens_deficit", models.FloatField(blank=True, null=True)),
                ("buff200_imd_deficit", models.FloatField(blank=True, null=True)),
                ("buff300_imd_deficit", models.FloatField(blank=True, null=True)),
                ("buff1k_imd_deficit", models.FloatField(blank=True, null=True)),
                ("buff2k_imd_deficit", models.FloatField(blank=True, null=True)),
                ("buff5k_imd_deficit", models.FloatField(blank=True, null=True)),
                ("buff10k_imd_deficit", models.FloatField(blank=True, null=True)),
                ("ag_area_ha", models.FloatField(blank=True, null=True)),
                (
                    "index_multiple_deprivation_2019",
                    models.FloatField(blank=True, null=True),
                ),
                ("population_estimate2018", models.IntegerField(blank=True, null=True)),
                (
                    "population_growth_2011_2018",
                    models.FloatField(blank=True, null=True),
                ),
                ("ethnic_white_2011", models.FloatField(blank=True, null=True)),
                ("ethnic_mixed_2011", models.FloatField(blank=True, null=True)),
                ("ethnic_asian_2011", models.FloatField(blank=True, null=True)),
                (
                    "ethnic_black_african_caribbean",
                    models.FloatField(blank=True, null=True),
                ),
                ("ethnic_other_2011", models.FloatField(blank=True, null=True)),
                ("population_2011_1000s", models.FloatField(blank=True, null=True)),
                ("nr_area_ha", models.FloatField(blank=True, null=True)),
                ("nr_percentage", models.FloatField(blank=True, null=True)),
                (
                    "ruc_category",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("ruc11", models.CharField(blank=True, max_length=2, null=True)),
                ("lnr_area_ha", models.FloatField(blank=True, null=True)),
                (
                    "residentialaddress_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("pg_area", models.FloatField(blank=True, null=True)),
                ("pg_area_per1kpeople", models.FloatField(blank=True, null=True)),
                ("perc_osmmgs", models.FloatField(blank=True, null=True)),
                ("pgarea_resaddress_ratio", models.FloatField(blank=True, null=True)),
                ("accessiblewoodland_ha", models.FloatField(blank=True, null=True)),
                ("mean_manmade_percentage", models.FloatField(blank=True, null=True)),
                ("cohort_age_0_to_4", models.IntegerField(blank=True, null=True)),
                ("cohort_age_5_to_7", models.IntegerField(blank=True, null=True)),
                ("cohort_age_8_to_9", models.IntegerField(blank=True, null=True)),
                ("cohort_age_10_to_14", models.IntegerField(blank=True, null=True)),
                ("cohort_age_15", models.IntegerField(blank=True, null=True)),
                ("cohort_age_16_to_17", models.IntegerField(blank=True, null=True)),
                ("cohort_age_18_to_19", models.IntegerField(blank=True, null=True)),
                ("cohort_age_20_to_24", models.IntegerField(blank=True, null=True)),
                ("cohort_age_25_to_29", models.IntegerField(blank=True, null=True)),
                ("cohort_age_30_to_44", models.IntegerField(blank=True, null=True)),
                ("cohort_age_45_to_59", models.IntegerField(blank=True, null=True)),
                ("cohort_age_60_to_64", models.IntegerField(blank=True, null=True)),
                ("cohort_age_65_to_74", models.IntegerField(blank=True, null=True)),
                ("cohort_age_75_to_84", models.IntegerField(blank=True, null=True)),
                ("cohort_age_85_to_89", models.IntegerField(blank=True, null=True)),
                ("cohort_age_90_and_over", models.IntegerField(blank=True, null=True)),
                ("perc_close2home", models.FloatField(blank=True, null=True)),
                ("popn_close2home", models.IntegerField(blank=True, null=True)),
                ("cohort_children", models.IntegerField(blank=True, null=True)),
                ("cohort_olderpeople", models.IntegerField(blank=True, null=True)),
                ("perc_pop_close2home", models.FloatField(blank=True, null=True)),
                (
                    "popn_children_close2home",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "popn_olderpeople_close2home",
                    models.IntegerField(blank=True, null=True),
                ),
                ("imd_reversed", models.FloatField(blank=True, null=True)),
                ("ag_area_ha_per_person", models.FloatField(blank=True, null=True)),
                (
                    "local_authority_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.localauthority",
                    ),
                ),
                (
                    "lsoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.lsoa",
                    ),
                ),
                (
                    "msoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.msoa",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population Density",
                "verbose_name_plural": "Population Densities",
            },
        ),
    ]
