# Generated by Django 4.1.7 on 2023-03-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "deprivation_scores",
            "0003_alter_indexmultipledeprivation_barriers_to_housing_services_score_exponentially_transformed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WelshIndexMultipleDeprivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imd_rank", models.IntegerField(max_length=50)),
                ("imd_quartile", models.SmallIntegerField()),
                ("imd_quintile", models.SmallIntegerField()),
                ("imd_decile", models.SmallIntegerField()),
                (
                    "imd_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("income_rank", models.IntegerField(max_length=50)),
                ("income_quartile", models.SmallIntegerField()),
                ("income_quintile", models.SmallIntegerField()),
                ("income_decile", models.SmallIntegerField()),
                (
                    "income_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("employment_rank", models.IntegerField(max_length=50)),
                ("employment_quartile", models.SmallIntegerField()),
                ("employment_quintile", models.SmallIntegerField()),
                ("employment_decile", models.SmallIntegerField()),
                (
                    "employment_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("health_rank", models.IntegerField(max_length=50)),
                ("health_quartile", models.SmallIntegerField()),
                ("health_quintile", models.SmallIntegerField()),
                ("health_decile", models.SmallIntegerField()),
                (
                    "health_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("education_rank", models.IntegerField(max_length=50)),
                ("education_quartile", models.SmallIntegerField()),
                ("education_quintile", models.SmallIntegerField()),
                ("education_decile", models.SmallIntegerField()),
                (
                    "education_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("access_to_services_rank", models.IntegerField(max_length=50)),
                ("access_to_services_quartile", models.SmallIntegerField()),
                ("access_to_services_quintile", models.SmallIntegerField()),
                ("access_to_services_decile", models.SmallIntegerField()),
                (
                    "access_to_services_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("housing_rank", models.IntegerField(max_length=50)),
                ("housing_quartile", models.SmallIntegerField()),
                ("housing_quintile", models.SmallIntegerField()),
                ("housing_decile", models.SmallIntegerField()),
                (
                    "housing_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("community_safety_rank", models.IntegerField(max_length=50)),
                ("community_safety_quartile", models.SmallIntegerField()),
                ("community_safety_quintile", models.SmallIntegerField()),
                ("community_safety_decile", models.SmallIntegerField()),
                (
                    "community_safety_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("physical_environment_rank", models.IntegerField(max_length=50)),
                ("physical_environment_quartile", models.SmallIntegerField()),
                ("physical_environment_quintile", models.SmallIntegerField()),
                ("physical_environment_decile", models.SmallIntegerField()),
                (
                    "physical_environment_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "lsoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deprivation_scores.lsoa",
                    ),
                ),
            ],
        ),
    ]
