# Generated by Django 6.0 on 2025-12-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0003_populationdensity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datazone",
            options={
                "verbose_name": ("Data Zone",),
                "verbose_name_plural": "Data Zones",
            },
        ),
        migrations.AlterModelOptions(
            name="englishindexmultipledeprivation",
            options={
                "verbose_name": ("English Index of Multiple Deprivation",),
                "verbose_name_plural": "English Indices of Multiple Deprivation",
            },
        ),
        migrations.AlterModelOptions(
            name="greenspace",
            options={
                "verbose_name": ("Green Space",),
                "verbose_name_plural": "Green Spaces",
            },
        ),
        migrations.AlterModelOptions(
            name="msoa",
            options={"verbose_name": ("MSOA",), "verbose_name_plural": "MSOAs"},
        ),
        migrations.AlterModelOptions(
            name="northernirelandindexmultipledeprivation",
            options={"verbose_name": ("SOA",), "verbose_name_plural": "SOAs"},
        ),
        migrations.AlterModelOptions(
            name="scottishindexmultipledeprivation",
            options={
                "verbose_name": ("Data Zone",),
                "verbose_name_plural": "Data Zones",
            },
        ),
        migrations.AlterModelOptions(
            name="soa",
            options={"verbose_name": ("SOA",), "verbose_name_plural": "SOAs"},
        ),
        migrations.AlterModelOptions(
            name="ward",
            options={"verbose_name": ("Ward",), "verbose_name_plural": "Wards"},
        ),
        migrations.AlterModelOptions(
            name="welshindexmultipledeprivation",
            options={
                "verbose_name": ("Welsh Index of Multiple Deprivation",),
                "verbose_name_plural": "Welsh Indices of Multiple Deprivation",
            },
        ),
        migrations.AddField(
            model_name="englishindexmultipledeprivation",
            name="year",
            field=models.IntegerField(null=True, verbose_name="Year"),
        ),
        migrations.AddField(
            model_name="greenspace",
            name="year",
            field=models.IntegerField(null=True, verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="datazone",
            name="data_zone_code",
            field=models.CharField(max_length=50, verbose_name="Data Zone Code"),
        ),
        migrations.AlterField(
            model_name="localauthority",
            name="local_authority_district_code",
            field=models.CharField(
                max_length=50, verbose_name="Local Authority District code (2019)"
            ),
        ),
        migrations.AlterField(
            model_name="lsoa",
            name="lsoa_code",
            field=models.CharField(max_length=50, verbose_name="LSOA code (2011)"),
        ),
        migrations.AlterField(
            model_name="msoa",
            name="msoa_code",
            field=models.CharField(
                help_text="Middle Layer Super Output Layer code",
                max_length=50,
                verbose_name="MSOA Code",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="ward_code",
            field=models.CharField(
                help_text="Ward code", max_length=50, verbose_name="Ward Code"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datazone",
            unique_together={("data_zone_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="englishindexmultipledeprivation",
            unique_together={("lsoa", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="greenspace",
            unique_together={("local_authority", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="localauthority",
            unique_together={("local_authority_district_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="lsoa",
            unique_together={("lsoa_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="msoa",
            unique_together={("msoa_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="northernirelandindexmultipledeprivation",
            unique_together={("soa", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="populationdensity",
            unique_together={("lsoa", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="scottishindexmultipledeprivation",
            unique_together={("data_zone", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="soa",
            unique_together={("soa_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("ward_code", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="welshindexmultipledeprivation",
            unique_together={("lsoa", "year")},
        ),
    ]
