# Generated by Django 4.1.7 on 2023-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deprivation_scores", "0004_welshindexmultipledeprivation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="access_to_services_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="community_safety_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="education_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="employment_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="health_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="housing_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="imd_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="income_rank",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="welshindexmultipledeprivation",
            name="physical_environment_rank",
            field=models.IntegerField(),
        ),
    ]
