# Generated by Django 6.0 on 2025-12-09 00:03

from django.db import migrations


def set_default_year(apps, schema_editor):
    EnglishIndexMultipleDeprivation = apps.get_model(
        "deprivation_scores", "EnglishIndexMultipleDeprivation"
    )
    GreenSpace = apps.get_model("deprivation_scores", "GreenSpace")
    EnglishIndexMultipleDeprivation.objects.filter(year__isnull=True).update(year=2019)
    GreenSpace.objects.filter(year__isnull=True).update(year=2020)


def reverse_func(apps, schema_editor):
    pass  # No need to reverse


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0004_alter_datazone_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_year, reverse_func),
    ]
