# Generated by Django 6.0 on 2025-12-22 20:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0005_set_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="localauthority",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="lsoa",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
