# Generated by Django 6.0 on 2025-12-24 23:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0006_localauthority_geom_lsoa_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="datazone",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="soa",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
