# Generated by Django 6.0.4 on 2026-04-18 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0007_datazone_geom_soa_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegratedCareBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icb_code",
                    models.CharField(
                        max_length=50, verbose_name="ICB Code (e.g., E54000001)"
                    ),
                ),
                ("icb_name", models.CharField(max_length=100, verbose_name="ICB Name")),
                (
                    "year",
                    models.IntegerField(default=2023, verbose_name="Boundary year"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrated Care Board",
                "verbose_name_plural": "Integrated Care Boards",
                "indexes": [
                    models.Index(fields=["year"], name="deprivation_year_01db2d_idx")
                ],
                "unique_together": {("icb_code", "year")},
            },
        ),
        migrations.CreateModel(
            name="LocalHealthBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lhb_code",
                    models.CharField(
                        max_length=50, verbose_name="LHB Code (e.g., W11000001)"
                    ),
                ),
                ("lhb_name", models.CharField(max_length=100, verbose_name="LHB Name")),
                (
                    "year",
                    models.IntegerField(default=2022, verbose_name="Boundary year"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Health Board",
                "verbose_name_plural": "Local Health Boards",
                "indexes": [
                    models.Index(fields=["year"], name="deprivation_year_05599d_idx")
                ],
                "unique_together": {("lhb_code", "year")},
            },
        ),
        migrations.CreateModel(
            name="NHSEnglishRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nhser_code",
                    models.CharField(
                        max_length=50,
                        verbose_name="NHS England Region Code (e.g., E40000001)",
                    ),
                ),
                (
                    "nhser_name",
                    models.CharField(
                        max_length=100,
                        verbose_name="NHS England Region Name (e.g., East of England)",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(default=2021, verbose_name="Boundary year"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "NHS England Region",
                "verbose_name_plural": "NHS England Regions",
                "indexes": [
                    models.Index(fields=["year"], name="deprivation_year_dee2a3_idx")
                ],
                "unique_together": {("nhser_code", "year")},
            },
        ),
    ]
