# Generated by Django 6.0.4 on 2026-05-15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deprivation_scores", "0008_integratedcareboard_localhealthboard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelIsland",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        verbose_name="ISO 3166-1 alpha-3 code (e.g. GGY, IMN, JEY)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Territory name"),
                ),
                (
                    "year",
                    models.IntegerField(default=2024, verbose_name="Boundary year"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Island / Crown Dependency",
                "verbose_name_plural": "Channel Islands / Crown Dependencies",
                "indexes": [
                    models.Index(
                        fields=["year"], name="deprivation_channelisland_year_idx"
                    )
                ],
                "unique_together": {("code", "year")},
            },
        ),
    ]
