# Generated by Django 4.2.8 on 2023-12-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rcpch_census_platform", "0006_seed_pdus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="trust",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trusts",
                to="rcpch_census_platform.trust",
            ),
        ),
    ]
