# Generated by Django 4.2.8 on 2023-12-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rcpch_census_platform", "0007_alter_organisation_trust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="trust",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisations",
                to="rcpch_census_platform.trust",
            ),
        ),
    ]
