# Generated by Django 4.2.8 on 2023-12-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rcpch_census_platform", "0008_alter_organisation_trust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="country_organisations",
                to="rcpch_census_platform.country",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="integrated_care_board",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrated_care_board_organisations",
                to="rcpch_census_platform.integratedcareboard",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="local_health_board",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_health_board_organisations",
                to="rcpch_census_platform.localhealthboard",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="london_borough",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="london_borough_organisations",
                to="rcpch_census_platform.londonborough",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="nhs_england_region",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nhs_england_region_organisations",
                to="rcpch_census_platform.nhsenglandregion",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="openuk_network",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="openuk_network_organisations",
                to="rcpch_census_platform.openuknetwork",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="paediatric_diabetes_unit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paediatric_diabetes_unit_organisations",
                to="rcpch_census_platform.paediatricdiabetesunit",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="trust",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_organisations",
                to="rcpch_census_platform.trust",
            ),
        ),
    ]
