# infra/azure/containerapp.template.yml
properties:
  environmentId: __AZURE_ENVIRONMENT_ID__
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 80
      transport: auto
      allowInsecure: false
  template:
    identity:
      type: UserAssigned
      userAssignedIdentities:
        "__IDENTITY_ID__": {}
    containers:
      # Nginx Reverse Proxy
      - name: nginx
        image: ghcr.io/rcpch/rcpch-census-nginx:__IMAGE_TAG__
        resources:
          cpu: 0.25
          memory: 0.5Gi # Increased to help hit total ratio

      # Django Web App
      - name: web
        image: ghcr.io/rcpch/rcpch-census-web:__IMAGE_TAG__
        env:
          - name: DEBUG
            value: "False"
          - name: POSTGRES_DB_HOST
            value: "__AZURE_POSTGRES_HOST__.postgres.database.azure.com"
          - name: POSTGRES_DB_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "__DB_NAME__"
          - name: POSTGRES_USER
            value: "__MANAGED_IDENTITY_NAME__"
          - name: DJANGO_SETTINGS_MODULE
            value: "rcpch_census_platform.settings"
        resources:
          cpu: 1.25 # Increased for DRF processing
          memory: 2.5Gi

      # pg_tileserv for vector tiles
      - name: tiles
        image: pramsey/pg_tileserv:latest
        env:
          - name: DATABASE_URL
            secretRef: tiles-db-url
        resources:
          cpu: 0.5
          memory: 1.0Gi # Increased for geometry caching
  