# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Autogenerate OpenAPI3 spec in YAML and JSON form and save to repo

on:
  push:
    branches:
      - **

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_CSRF_TRUSTED_ORIGINS: https://localhost,https://0.0.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install yq 
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      
      - name: Create openAPI.yml
        run: python manage.py spectacular --file openapi.yml        

      - name: Convert yaml to json
        run: yq -o=json '.' openapi.yml > openapi.json
        
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'openapi.json'
          commit_message: 'Autogenerated openapi3.yml and openapi.json'
      
